/**
 * EXCRETION IN PLANTS: the lesson (Class 10 · NCERT §5.5.2)
 *
 * BASIC IDEA (01) → QUESTION (01) → PROBLEM (02) → DISCOVERY / PROCESS / EXPLANATION /
 * INTERACTION (03: six processes, followed one at a time) → SUMMARY (04) → RECALL (05)
 *
 * Chapter 03 is one journey in six sections. Sections are named by WHERE the camera goes,
 * never by the answer, so nothing is named before it has been seen.
 *
 * SHOT FIELDS
 *   id               stable id: narration clip, QA and audit key
 *   section          (chapter 03) which part of the journey
 *   cameraTarget     { preset, from, transitionMs, endScale, compose, follow }   presets: shots.js
 *   narration        what the teacher says (Google TTS clip per shot)
 *   caption          the concise on-screen idea: one line per spoken sentence (or one line for the shot)
 *   heading          topic heading, top-left: { eyebrow, title, text, appearAtMs } (never read aloud word for word)
 *   highlightObjects scene nodes lifted with the warm highlight
 *   view             { stage, soil:'shell', dim, labels:[≤5], veil:'in'|'out', insets, figure }
 *   animation        processes started on this shot: { process, mode, through: shotId|'END' }
 *   interaction      a "Your turn" (the film waits for it)
 *   duration         { minMs, tailMs } — otherwise the shot lasts as long as its narration
 *   a11y             plain description of the frame for screen readers
 *
 * Every string here is original teaching text checked against the NCERT pages in /ncert
 * (docs/ncert-content-audit.md). Processes are pure functions of lesson time, so the
 * film can be paused, scrubbed or replayed anywhere.
 */

const FOLLOW = 'Follow the waste';
const CELL_PATH = 'Plant › Leaf › Tissue › Cell';
const MAP = MAP_LABELS();

export const LESSON = {
  id: 'excretion-in-plants',
  title: 'Excretion in Plants',
  subtitle: 'Class 10 Biology',
  thesis: 'A plant has no organ like a kidney. So where does its waste go?',
  centralQuestion: 'Plants do not have one specialised excretory organ like animals. So how do plants deal with their wastes?',

  chapters: [
    // ================================================================== 01
    {
      id: 'what',
      number: '01',
      title: 'What is excretion?',
      shots: [
        {
          id: 'what.alive',
          cameraTarget: { preset: 'plantIntro', transitionMs: 0, endScale: 0.9, compose: 'right' },
          narration: 'This plant is alive. Like every living thing, it has to keep working just to stay alive.',
          caption: ['This plant is alive.', 'It keeps working to stay alive.'],
          heading: { title: 'A living plant', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'A young green plant standing in a block of soil.',
        },
        {
          id: 'what.processes',
          cameraTarget: { preset: 'plantWide', transitionMs: 2600, endScale: 0.94, compose: 'right' },
          narration: 'The jobs that keep it alive are called life processes. A plant makes its own food, and breaks food down to get energy.',
          caption: ['Jobs that keep it alive: life processes.', 'It makes food, and gets energy from it.'],
          heading: { title: 'Staying alive', text: 'Life processes: making food, getting energy', appearAtMs: 700 },
          view: { stage: 'plant' },
          a11y: 'The whole plant, slowly turning.',
        },
        {
          id: 'what.byproducts',
          cameraTarget: { preset: 'plantCanopy', transitionMs: 2200, endScale: 0.9, compose: 'right' },
          narration: 'But life processes also make substances the plant does not need. Some of them could even harm it if they stayed.',
          caption: ['Life processes also make unwanted substances.', 'Some could even be harmful.'],
          heading: { title: 'Substances it does not need', appearAtMs: 900 },
          view: { stage: 'plant' },
          animation: [{ process: 'intro', mode: 'wastes', through: 'what.question' }],
          duration: { minMs: 8500 },
          a11y: 'Small purple particles, the unwanted substances, appear inside the leaves and stem.',
        },
        {
          id: 'what.excretion',
          cameraTarget: { preset: 'plantCanopy', transitionMs: 1200, endScale: 0.82, compose: 'right' },
          narration: 'Removing these harmful wastes from the body is called excretion. Every living thing has to do it in some way.',
          caption: ['Removing harmful wastes: excretion.', 'Every living thing must do it.'],
          heading: { title: 'Excretion', text: 'Getting rid of harmful wastes', appearAtMs: 700 },
          view: { stage: 'plant' },
          a11y: 'The purple waste particles glow inside the plant.',
        },
        {
          id: 'what.question',
          cameraTarget: { preset: 'plantWide', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'Plants also carry out life processes. So what happens to the substances they do not need?',
          caption: ['Plants carry out life processes too.', 'So where do their unwanted substances go?'],
          heading: { title: 'What happens to a plant’s wastes?', appearAtMs: 900 },
          view: { stage: 'plant' },
          duration: { tailMs: 1600 },
          a11y: 'The whole plant, with its wastes inside.',
        },
      ],
    },

    // ================================================================== 02
    {
      id: 'different',
      number: '02',
      title: 'Why is plant excretion different?',
      shots: [
        {
          id: 'different.animals',
          cameraTarget: { preset: 'plantWide', transitionMs: 1400, endScale: 0.96, compose: 'right' },
          narration: 'Many animals, like us, have special organs for this job. Our two kidneys filter wastes out of the blood.',
          caption: ['Animals have special organs for excretion.', 'Our kidneys filter wastes from the blood.'],
          heading: { title: 'Animals use special organs', appearAtMs: 700 },
          view: { stage: 'plant' },
          animation: [{ process: 'figure', mode: 'kidneys', through: 'different.none' }],
          a11y: 'A small drawing of a human body with the two kidneys marked, beside the plant.',
        },
        {
          id: 'different.parts',
          cameraTarget: { preset: 'plantFront', transitionMs: 2200, endScale: 0.95, compose: 'right' },
          narration: 'Now look at the plant. It has leaves, a stem with branches, and roots in the soil.',
          caption: 'Leaves, a stem with branches, and roots.',
          heading: { title: 'Leaves, stem, roots', appearAtMs: 700 },
          view: {
            stage: 'plant',
            soil: 'shell',
            labels: [
              { anchor: 'Leaf_Hero', text: 'Leaves', dir: 'left', atMs: 1600 },
              { anchor: 'ANCHOR_Plant_Center', text: 'Stem and branches', dir: 'right', atMs: 3000 },
              { anchor: 'ANCHOR_Root_Zone', text: 'Roots', dir: 'right', atMs: 4600 },
            ],
          },
          animation: [{ process: 'partsTour' }],
          duration: { minMs: 8000 },
          a11y: 'The soil turns see-through. The leaves, then the stem and branches, then the roots light up in turn.',
        },
        {
          id: 'different.none',
          cameraTarget: { preset: 'plantWide', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'But none of these parts works like a kidney. Plants use completely different ways to deal with their wastes.',
          caption: ['No part works like a kidney.', 'Plants use completely different ways.'],
          heading: { title: 'No organ like a kidney', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant again, with no part lit up.',
        },
        {
          id: 'different.question',
          cameraTarget: { preset: 'plantQuestion', transitionMs: 2200, endScale: 0.9, compose: 'right' },
          narration: 'So here is our big question. If a plant has no special excretory organ, what does it do with its wastes?',
          caption: ['Our big question:', 'No excretory organ… so what happens to its wastes?'],
          heading: { eyebrow: 'The big question', title: 'So how does a plant deal with its wastes?', appearAtMs: 600 },
          view: { stage: 'plant' },
          duration: { tailMs: 2800 },
          a11y: 'A slow move towards the plant while the question stays on screen.',
        },
        {
          id: 'different.plan',
          cameraTarget: { preset: 'plantWide', transitionMs: 1800, endScale: 0.94, compose: 'right' },
          narration: 'Let’s find out. We will follow the waste through the plant, one place at a time, starting high up at a leaf.',
          caption: 'We’ll follow the waste, place by place.',
          heading: { title: 'Where does the waste go?', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
      ],
    },

    // ================================================================== 03
    {
      id: 'follow',
      number: '03',
      title: FOLLOW,
      sections: [
        { id: 'oxygen', title: 'At a leaf' },
        { id: 'water', title: 'Water in the plant' },
        { id: 'vacuole', title: 'Inside a cell' },
        { id: 'leaves', title: 'An older leaf' },
        { id: 'resin', title: 'Inside the stem' },
        { id: 'soil', title: 'Around the roots' },
      ],
      shots: [
        // ---------------------------------------------------------- 3.1 oxygen
        {
          id: 'oxygen.travel',
          section: 'oxygen',
          cameraTarget: { preset: 'leafApproach', transitionMs: 3200, endScale: 0.94, compose: 'right' },
          narration: 'Our first stop is a leaf, high up on the plant.',
          caption: 'First stop: a leaf.',
          heading: { eyebrow: FOLLOW, title: 'Start at a leaf', appearAtMs: 2200 },
          view: { stage: 'plant' },
          a11y: 'The camera rises through the plant to one large leaf.',
        },
        {
          id: 'oxygen.look',
          section: 'oxygen',
          cameraTarget: { preset: 'leafHero', transitionMs: 1800, endScale: 0.94, compose: 'right' },
          narration: 'Leaves make the plant’s food. They do it by a process called photosynthesis.',
          caption: ['Leaves make the plant’s food…', '…by photosynthesis.'],
          heading: { eyebrow: FOLLOW, title: 'Where food is made', appearAtMs: 700 },
          highlightObjects: ['Leaf_Hero'],
          view: { stage: 'plant' },
          a11y: 'A close view of one leaf with its veins.',
        },
        {
          id: 'oxygen.photo',
          section: 'oxygen',
          cameraTarget: { preset: 'leafHero', transitionMs: 800, endScale: 0.9, compose: 'right' },
          narration: 'In sunlight, the leaf uses carbon dioxide and water to make food.',
          caption: 'Sunlight: carbon dioxide + water → food.',
          heading: { eyebrow: FOLLOW, title: 'Photosynthesis', text: 'Sunlight, carbon dioxide and water make food', appearAtMs: 900 },
          view: { stage: 'plant' },
          animation: [{ process: 'sunlight', through: 'oxygen.reason' }],
          duration: { minMs: 6500 },
          a11y: 'A soft shaft of sunlight falls on the leaf and it glows gently.',
        },
        {
          id: 'oxygen.produce',
          section: 'oxygen',
          cameraTarget: { preset: 'leafHero', transitionMs: 600, endScale: 0.86, compose: 'right' },
          narration: 'Photosynthesis also makes a gas: oxygen. Watch it form in the leaf.',
          caption: ['Photosynthesis also makes oxygen.', 'Watch it form.'],
          heading: { eyebrow: FOLLOW, title: 'Something else is made', appearAtMs: 1400 },
          view: { stage: 'plant', labels: [{ anchor: 'ANCHOR_Leaf_Hero_Normal', text: 'Oxygen', dir: 'right' }] },
          animation: [{ process: 'oxygen', mode: 'form' }],
          duration: { minMs: 7000 },
          a11y: 'Small pairs of pale blue spheres, oxygen, form on the leaf.',
        },
        {
          id: 'oxygen.release',
          section: 'oxygen',
          cameraTarget: { preset: 'leafAir', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'The oxygen passes out of the leaf, into the air around the plant.',
          caption: 'Oxygen leaves the leaf, into the air.',
          heading: { eyebrow: FOLLOW, title: 'Out into the air', appearAtMs: 1200 },
          view: { stage: 'plant' },
          animation: [{ process: 'oxygen', mode: 'release', through: 'oxygen.reason' }],
          duration: { minMs: 7500 },
          a11y: 'The oxygen rises away from the leaf into the air.',
        },
        {
          id: 'oxygen.reason',
          section: 'oxygen',
          cameraTarget: { preset: 'leafAir', transitionMs: 900, endScale: 0.9, compose: 'right' },
          narration: 'The plant makes this oxygen and then gives it out. So oxygen can be thought of as a waste product of photosynthesis, and the plant gets rid of it by releasing it into the air.',
          caption: ['Made, then given out.', 'Oxygen: a waste product, released into the air.'],
          heading: { eyebrow: FOLLOW, title: 'Oxygen as waste', appearAtMs: 800 },
          view: { stage: 'plant' },
          a11y: 'Oxygen keeps rising from the leaf.',
        },
        {
          id: 'oxygen.try',
          section: 'oxygen',
          cameraTarget: { preset: 'leafAir', transitionMs: 900, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. Bring the sunlight to the leaf, and watch what comes out of it.',
          caption: 'Your turn: bring sunlight to the leaf.',
          heading: { eyebrow: 'Your turn', title: 'Sunlight on the leaf', appearAtMs: 500 },
          view: { stage: 'plant' },
          interaction: {
            kind: 'sunlight',
            task: 'Drag the slider to bring sunlight to the leaf.',
            done: 'With sunlight, the leaf makes food, and oxygen leaves it.',
          },
          a11y: 'A slider controls the sunlight falling on the leaf.',
        },

        // ---------------------------------------------------------- 3.2 water
        {
          id: 'water.question',
          section: 'water',
          cameraTarget: { preset: 'leafHero', transitionMs: 1600, endScale: 0.95, compose: 'right' },
          narration: 'A plant also takes in a lot of water, often more than it needs. What happens to the extra water?',
          caption: ['Plants take in lots of water.', 'What happens to the extra?'],
          heading: { eyebrow: FOLLOW, title: 'Too much water?', appearAtMs: 800 },
          view: { stage: 'plant' },
          duration: { tailMs: 1000 },
          a11y: 'The leaf again.',
        },
        {
          id: 'water.enter',
          section: 'water',
          cameraTarget: { preset: 'waterRoots', transitionMs: 3400, endScale: 0.94, compose: 'right' },
          narration: 'Water from the soil enters the plant through its roots.',
          caption: 'Water enters through the roots.',
          heading: { eyebrow: FOLLOW, title: 'In at the roots', appearAtMs: 2400 },
          view: { stage: 'plant', soil: 'shell' },
          animation: [{ process: 'water', mode: 'enter' }],
          duration: { minMs: 7500 },
          a11y: 'The soil becomes see-through. Blue drops of water move from the soil into a root.',
        },
        {
          id: 'water.rise',
          section: 'water',
          cameraTarget: { preset: 'waterRoots', transitionMs: 1200, follow: { process: 'water', target: 'lead' }, compose: 'center' },
          narration: 'It moves up the stem inside tubes called xylem, and out along the branches to the leaves.',
          caption: 'Up the stem in xylem tubes, out to the leaves.',
          heading: { eyebrow: FOLLOW, title: 'Up through the plant', appearAtMs: 900 },
          view: { stage: 'plant', soil: 'shell' },
          animation: [{ process: 'water', mode: 'rise' }],
          duration: { minMs: 9500 },
          a11y: 'The camera follows a drop of water as it climbs up inside the stem to a leaf.',
        },
        {
          id: 'water.vapour',
          section: 'water',
          cameraTarget: { preset: 'leafAir', transitionMs: 1400, endScale: 0.94, compose: 'right' },
          narration: 'In the leaves, some of this water turns into water vapour and escapes into the air.',
          caption: 'In the leaves, water escapes as vapour.',
          heading: { eyebrow: FOLLOW, title: 'Out as vapour', appearAtMs: 1200 },
          view: { stage: 'plant', labels: [{ anchor: 'ANCHOR_Leaf_Hero_Normal', text: 'Water vapour', dir: 'right' }] },
          animation: [{ process: 'water', mode: 'vapour' }],
          duration: { minMs: 7500 },
          a11y: 'Soft white puffs of water vapour drift up from the leaf.',
        },
        {
          id: 'water.reason',
          section: 'water',
          cameraTarget: { preset: 'waterWide', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'Losing water as vapour like this is called transpiration. It is how a plant gets rid of its excess water.',
          caption: ['Losing water as vapour: transpiration.', 'It gets rid of excess water.'],
          heading: { eyebrow: FOLLOW, title: 'Transpiration', text: 'Excess water leaves as vapour', appearAtMs: 1000 },
          view: { stage: 'plant', soil: 'shell' },
          animation: [{ process: 'water', mode: 'cycle' }],
          a11y: 'The whole plant: water rises from the roots and vapour leaves the leaves.',
        },

        // ---------------------------------------------------------- 3.3 vacuole (scale journey)
        {
          id: 'vacuole.pivot',
          section: 'vacuole',
          cameraTarget: { preset: 'plantWide', transitionMs: 2200, endScale: 0.95, compose: 'right' },
          narration: 'Oxygen and extra water leave the plant. But some wastes are not removed at all. They are kept inside the plant.',
          caption: ['Oxygen and water leave the plant.', 'Some wastes are not removed…', '…they are kept inside.'],
          heading: { eyebrow: FOLLOW, title: 'Not every waste leaves', text: 'Remove, or store?', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
        {
          id: 'vacuole.dive',
          section: 'vacuole',
          cameraTarget: { preset: 'leafDive', transitionMs: 3200, compose: 'center' },
          narration: 'To see where, we need to zoom right into a leaf.',
          caption: 'Zooming into a leaf…',
          heading: { eyebrow: 'Plant › Leaf', title: 'Closer', appearAtMs: 600 },
          view: { stage: 'plant', veil: 'in' },
          duration: { minMs: 5200 },
          a11y: 'The camera moves right up to the surface of the leaf.',
        },
        {
          id: 'vacuole.tissue',
          section: 'vacuole',
          cameraTarget: { preset: 'tissueWide', from: 'tissueFar', transitionMs: 0, endScale: 0.9, compose: 'right' },
          narration: 'Up close, a leaf is made of many tiny cells, packed together.',
          caption: 'A leaf is made of many tiny cells.',
          heading: { eyebrow: 'Plant › Leaf › Tissue', title: 'Many cells', appearAtMs: 1200 },
          view: { stage: 'cell', veil: 'out' },
          duration: { minMs: 6500 },
          a11y: 'A magnified slice of leaf: rows of green cells.',
        },
        {
          id: 'vacuole.cell',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', transitionMs: 3000, endScale: 0.94, compose: 'right' },
          narration: 'Here is one of those cells, opened up. It has a cell wall, jelly-like cytoplasm, a nucleus, and one large vacuole.',
          caption: ['One plant cell, opened up.', 'Wall, cytoplasm, nucleus, one large vacuole.'],
          heading: { eyebrow: CELL_PATH, title: 'One plant cell', appearAtMs: 2200 },
          view: {
            stage: 'cell',
            labels: [
              { anchor: 'ANCHOR_Cell_Wall', text: 'Cell wall', dir: 'right' },
              { anchor: 'ANCHOR_Cytoplasm', text: 'Cytoplasm', dir: 'left' },
              { anchor: 'ANCHOR_Nucleus', text: 'Nucleus', dir: 'left' },
              { anchor: 'ANCHOR_Vacuole_Front', text: 'Vacuole', dir: 'right' },
            ],
          },
          a11y: 'One cell cut open, showing its wall, cytoplasm, nucleus and a large vacuole.',
        },
        {
          id: 'vacuole.store',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', transitionMs: 600, endScale: 0.86, compose: 'right' },
          narration: 'Now watch the wastes in the cytoplasm. They move into the vacuole, and there they stay.',
          caption: ['Watch the wastes…', '…they move into the vacuole and stay.'],
          heading: { eyebrow: CELL_PATH, title: 'Where the wastes go', appearAtMs: 1800 },
          view: { stage: 'cell' },
          animation: [{ process: 'vacuole', mode: 'store', through: 'END' }],
          duration: { minMs: 9000 },
          a11y: 'Purple waste particles drift into the vacuole and stay there.',
        },
        {
          id: 'vacuole.reason',
          section: 'vacuole',
          cameraTarget: { preset: 'vacuole', transitionMs: 2000, endScale: 0.94, compose: 'right' },
          narration: 'The vacuole is a storage space inside the cell. Many plant waste products are stored in vacuoles like this one. They are kept, not removed from the plant.',
          caption: ['The vacuole: a storage space.', 'Many plant wastes are stored in vacuoles.', 'Kept inside, not removed.'],
          heading: { eyebrow: `${CELL_PATH} › Vacuole`, title: 'Stored, not removed', appearAtMs: 900 },
          highlightObjects: ['Vacuole'],
          view: { stage: 'cell', labels: [{ anchor: 'ANCHOR_Vacuole_Front', text: 'Stored wastes', dir: 'right' }] },
          a11y: 'A close view of the vacuole holding the wastes.',
        },
        {
          id: 'vacuole.try',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', transitionMs: 1600, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. A few wastes are still in the cytoplasm. Move them into the vacuole.',
          caption: 'Your turn: store the last wastes.',
          heading: { eyebrow: 'Your turn', title: 'Store the wastes', appearAtMs: 500 },
          view: { stage: 'cell' },
          interaction: {
            kind: 'storeWaste',
            task: 'Tap each purple waste, or use the button, to move it into the vacuole.',
            done: 'Stored. The wastes stay inside the vacuole.',
          },
          a11y: 'Three wastes wait in the cytoplasm. Tapping one moves it into the vacuole.',
        },
        {
          id: 'vacuole.back',
          section: 'vacuole',
          cameraTarget: { preset: 'tissueFar', transitionMs: 3000, compose: 'center' },
          narration: 'Now let’s pull back out: from the vacuole, to the cell, to the leaf.',
          caption: 'Vacuole → cell → leaf…',
          heading: { eyebrow: 'Vacuole › Cell › Leaf', title: 'Pulling back', appearAtMs: 600 },
          view: { stage: 'cell', veil: 'in' },
          duration: { minMs: 5200 },
          a11y: 'The camera pulls back from the vacuole, past the cell, to the whole slice of leaf.',
        },
        {
          id: 'vacuole.plant',
          section: 'vacuole',
          cameraTarget: { preset: 'plantWide', from: 'leafDive', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'And back to the whole plant. Its leaves are made of cells like the one we just saw.',
          caption: ['…and back to the whole plant.', 'Its leaves are made of cells like that one.'],
          heading: { eyebrow: 'Leaf › Plant', title: 'The whole plant again', appearAtMs: 1800 },
          view: { stage: 'plant', veil: 'out' },
          a11y: 'The camera pulls back from the leaf surface to the whole plant.',
        },

        // ---------------------------------------------------------- 3.4 leaves
        {
          id: 'leaves.lose',
          section: 'leaves',
          cameraTarget: { preset: 'plantWide', transitionMs: 1400, endScale: 0.94, compose: 'right' },
          narration: 'Plants have another useful ability. They can even lose some of their parts, such as leaves.',
          caption: ['Plants have another useful ability.', 'They can lose some parts, like leaves.'],
          heading: { eyebrow: FOLLOW, title: 'Losing parts', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
        {
          id: 'leaves.look',
          section: 'leaves',
          cameraTarget: { preset: 'leafOld', transitionMs: 2600, endScale: 0.94, compose: 'right' },
          narration: 'Look at this leaf, low down on the stem. It is one of the plant’s older leaves.',
          caption: 'An older leaf, low on the stem.',
          heading: { eyebrow: FOLLOW, title: 'Low on the stem', appearAtMs: 1600 },
          highlightObjects: ['Leaf_Old'],
          view: { stage: 'plant', labels: [{ anchor: 'Leaf_Old', text: 'An older leaf', dir: 'right' }] },
          a11y: 'A close view of an older leaf low on the stem.',
        },
        {
          id: 'leaves.load',
          section: 'leaves',
          cameraTarget: { preset: 'leafOld', transitionMs: 600, endScale: 0.88, compose: 'right' },
          narration: 'Some waste products are stored in leaves like this one. Time passes, and the leaf grows older.',
          caption: ['Some wastes are stored in the leaf.', 'Time passes…'],
          heading: { eyebrow: FOLLOW, title: 'Stored in the leaf', appearAtMs: 1600 },
          view: { stage: 'plant' },
          animation: [{ process: 'leafFall', through: 'END' }],
          duration: { minMs: 9000 },
          a11y: 'Purple wastes gather in the older leaf, which slowly turns yellow.',
        },
        {
          id: 'leaves.fall',
          section: 'leaves',
          cameraTarget: { preset: 'leafFall', transitionMs: 1400, endScale: 0.96, compose: 'right' },
          narration: 'Then the leaf drops off the plant.',
          caption: 'The leaf falls off.',
          heading: { eyebrow: FOLLOW, title: 'Lost from the plant', appearAtMs: 1200 },
          view: { stage: 'plant' },
          duration: { minMs: 6000 },
          a11y: 'The old leaf breaks away and flutters down onto the soil.',
        },
        {
          id: 'leaves.reason',
          section: 'leaves',
          cameraTarget: { preset: 'leafFallen', transitionMs: 2000, endScale: 0.94, compose: 'right' },
          narration: 'When the leaf falls, the wastes stored in it leave the plant too. Leaves also fall for other reasons, but this is one way a plant gets rid of wastes.',
          caption: ['Stored wastes leave with the fallen leaf.', 'Not the only reason leaves fall, but one way to lose wastes.'],
          heading: { eyebrow: FOLLOW, title: 'Wastes leave with it', appearAtMs: 900 },
          view: { stage: 'plant', labels: [{ anchor: 'Leaf_Old', text: 'Stored wastes', dir: 'right' }] },
          a11y: 'The fallen leaf lies on the soil, still holding its wastes.',
        },

        // ---------------------------------------------------------- 3.5 resins and gums
        {
          id: 'resin.travel',
          section: 'resin',
          cameraTarget: { preset: 'stemCut', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'Next, the stem. It looks solid from the outside, so let’s look inside it.',
          caption: 'Next: inside the stem.',
          heading: { eyebrow: FOLLOW, title: 'Into the stem', appearAtMs: 2200 },
          highlightObjects: ['Stem_Main'],
          view: { stage: 'plant' },
          animation: [{ process: 'cutRing' }],
          a11y: 'A close view of the lower stem with a thin ring marking where it will be opened.',
        },
        {
          id: 'resin.cut',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', from: 'stemIntact', transitionMs: 0, endScale: 1, compose: 'right' },
          narration: 'Here is a magnified piece of the stem. As the top lifts away, we can see its layers.',
          caption: 'A magnified piece of stem, opened up.',
          heading: { eyebrow: 'Stem › Inside', title: 'A slice of stem', appearAtMs: 1000 },
          view: { stage: 'stem', veil: 'out' },
          animation: [{ process: 'stemCover', through: 'END' }],
          duration: { minMs: 7500 },
          a11y: 'A piece of stem; its top lifts away to show the layers inside.',
        },
        {
          id: 'resin.layers',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', transitionMs: 800, endScale: 0.95, compose: 'right' },
          narration: 'Bark covers the outside. Inside are phloem, which carries food, and xylem, the same kind of tubes that carried water up the stem.',
          caption: ['Bark covers the outside.', 'Inside: phloem carries food, xylem carries water.'],
          heading: { eyebrow: 'Stem › Inside', title: 'Layers inside', appearAtMs: 900 },
          view: {
            stage: 'stem',
            labels: [
              { anchor: 'ANCHOR_Bark', text: 'Bark', dir: 'left' },
              { anchor: 'ANCHOR_Phloem', text: 'Phloem', dir: 'left' },
              { anchor: 'ANCHOR_Xylem_New', text: 'Xylem', dir: 'left' },
            ],
          },
          a11y: 'Rings of tissue labelled bark, phloem and xylem.',
        },
        {
          id: 'resin.old',
          section: 'resin',
          cameraTarget: { preset: 'stemOldXylem', transitionMs: 2000, endScale: 0.95, compose: 'right' },
          narration: 'This darker part is old xylem. Like many plant tissues, it is made mostly of dead cells.',
          caption: ['This is old xylem.', 'Like many plant tissues: mostly dead cells.'],
          heading: { eyebrow: 'Stem › Inside', title: 'Old, dead cells', appearAtMs: 900 },
          highlightObjects: ['Xylem_Old'],
          view: { stage: 'stem', dim: true, labels: [{ anchor: 'ANCHOR_Xylem_Old', text: 'Old xylem', dir: 'right' }] },
          a11y: 'Only the darker ring, the old xylem, stays bright; the other layers are darkened.',
        },
        {
          id: 'resin.store',
          section: 'resin',
          cameraTarget: { preset: 'stemOldXylem', transitionMs: 600, endScale: 0.88, compose: 'right' },
          narration: 'Watch. Some waste products are stored here, as resins and gums.',
          caption: 'Wastes are stored here as resins and gums.',
          heading: { eyebrow: 'Stem › Inside', title: 'A store in the stem', appearAtMs: 1600 },
          highlightObjects: ['Xylem_Old'],
          view: { stage: 'stem', dim: true },
          animation: [{ process: 'resin', through: 'END' }],
          duration: { minMs: 9000 },
          a11y: 'Purple wastes move into the old xylem and become amber drops of resin and gum.',
        },
        {
          id: 'resin.reason',
          section: 'resin',
          cameraTarget: { preset: 'stemOrbit', transitionMs: 2200, endScale: 0.96, compose: 'right' },
          narration: 'So other waste products are stored as resins and gums, especially in old xylem. They are kept inside the stem, not removed.',
          caption: ['Resins and gums: stored, especially in old xylem.', 'Kept, not removed.'],
          heading: { eyebrow: 'Stem › Inside', title: 'Especially old xylem', appearAtMs: 900 },
          view: { stage: 'stem', labels: [{ anchor: 'Resin_03', text: 'Resins and gums', dir: 'right' }, { anchor: 'ANCHOR_Xylem_Old_Face', text: 'Old xylem', dir: 'left' }] },
          a11y: 'The stem slice with amber resin and gum drops inside the old xylem.',
        },
        {
          id: 'resin.try',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', transitionMs: 1600, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. Find the part of the stem where resins and gums are stored.',
          caption: 'Your turn: find where resins and gums are stored.',
          heading: { eyebrow: 'Your turn', title: 'Find the store', appearAtMs: 500 },
          view: { stage: 'stem' },
          interaction: {
            kind: 'findTissue',
            task: 'Tap the part of the stem where resins and gums are stored, or choose it below.',
            target: 'old_xylem',
            done: 'Yes. Resins and gums are stored especially in old xylem.',
            wrong: 'Not that part. Look for the amber drops.',
            choices: [
              { part: 'bark', label: 'Bark' },
              { part: 'phloem', label: 'Phloem' },
              { part: 'xylem', label: 'Xylem' },
              { part: 'old_xylem', label: 'Old xylem' },
            ],
          },
          a11y: 'The stem slice. Tap a layer, or choose one from the list, to answer.',
        },

        // ---------------------------------------------------------- 3.6 soil
        {
          id: 'soil.travel',
          section: 'soil',
          cameraTarget: { preset: 'roots', from: 'stemMid', transitionMs: 3600, endScale: 0.95, compose: 'right' },
          narration: 'Our last stop is below the ground, around the roots.',
          caption: 'Last stop: around the roots.',
          heading: { eyebrow: FOLLOW, title: 'Under the soil', appearAtMs: 2600 },
          view: { stage: 'plant', soil: 'shell', veil: 'out' },
          a11y: 'The camera moves down the stem, below the soil, to the roots.',
        },
        {
          id: 'soil.look',
          section: 'soil',
          cameraTarget: { preset: 'roots', transitionMs: 600, endScale: 0.9, compose: 'right' },
          narration: 'The roots spread out through the soil, and the soil surrounds them on every side.',
          caption: 'Soil surrounds the roots.',
          heading: { eyebrow: FOLLOW, title: 'Roots in soil', appearAtMs: 900 },
          highlightObjects: ['Roots'],
          view: { stage: 'plant', soil: 'shell', labels: [{ anchor: 'ANCHOR_Root_Zone', text: 'Roots', dir: 'right' }, { anchor: 'ANCHOR_Soil_Cut_Face', text: 'Soil', dir: 'left' }] },
          a11y: 'The roots, lit up, spread through the soil.',
        },
        {
          id: 'soil.excrete',
          section: 'soil',
          cameraTarget: { preset: 'rootsClose', transitionMs: 1800, endScale: 0.92, compose: 'right' },
          narration: 'Watch closely. Some waste substances pass out of the plant, into the soil around the roots.',
          caption: ['Watch closely.', 'Some wastes pass into the soil.'],
          heading: { eyebrow: FOLLOW, title: 'Out into the soil', appearAtMs: 1600 },
          view: { stage: 'plant', soil: 'shell' },
          animation: [{ process: 'soil', through: 'soil.reason' }],
          duration: { minMs: 8500 },
          a11y: 'A few purple particles drift from the roots out into the soil.',
        },
        {
          id: 'soil.reason',
          section: 'soil',
          cameraTarget: { preset: 'roots', transitionMs: 1600, endScale: 0.95, compose: 'right' },
          narration: 'So plants also excrete some waste substances into the soil around them.',
          caption: 'Plants excrete some wastes into the soil.',
          heading: { eyebrow: FOLLOW, title: 'Excreted into the soil', appearAtMs: 900 },
          view: { stage: 'plant', soil: 'shell' },
          a11y: 'The roots and the soil around them.',
        },
      ],
    },

    // ================================================================== 04
    {
      id: 'whole',
      number: '04',
      title: 'The whole picture',
      shots: [
        {
          id: 'whole.return',
          cameraTarget: { preset: 'final', transitionMs: 3600, endScale: 0.96, compose: 'right' },
          narration: 'Now let’s put the whole journey together, on one plant.',
          caption: 'Putting it all together.',
          heading: { title: 'Back to the whole plant', appearAtMs: 2400 },
          view: { stage: 'plant', soil: 'shell' },
          a11y: 'The whole plant, with the roots visible.',
        },
        {
          id: 'whole.oxygen',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.95, compose: 'right' },
          narration: 'From the leaves, oxygen made in photosynthesis is released into the air.',
          caption: 'Leaf → oxygen → air',
          heading: { title: 'Released', text: 'Oxygen, from the leaves', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', labels: [MAP.oxygen] },
          animation: [{ process: 'oxygen', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Oxygen rises from the leaves.',
        },
        {
          id: 'whole.water',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.94, compose: 'right' },
          narration: 'Excess water is lost from the leaves as water vapour. That is transpiration.',
          caption: 'Leaf → excess water → air',
          heading: { title: 'Removed', text: 'Excess water, as vapour', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', labels: [MAP.oxygen, MAP.water] },
          animation: [{ process: 'water', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Water vapour drifts up from the leaves.',
        },
        {
          id: 'whole.vacuole',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.935, compose: 'right' },
          narration: 'Inside the cells, many wastes are stored in vacuoles.',
          caption: 'Cell → waste → vacuole',
          heading: { title: 'Stored in cells', text: 'In cellular vacuoles', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell'], labels: [MAP.oxygen, MAP.water, MAP.vacuole] },
          a11y: 'A small round window opens beside a leaf, showing the cell vacuole holding wastes.',
        },
        {
          id: 'whole.leaf',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.93, compose: 'right' },
          narration: 'Some wastes are stored in leaves, which later fall off and take the wastes with them.',
          caption: 'Leaf → stored waste → leaf fall',
          heading: { title: 'Lost with leaves', text: 'Stored, then shed', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell'], labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf] },
          a11y: 'The fallen leaf on the soil is picked out.',
        },
        {
          id: 'whole.xylem',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.925, compose: 'right' },
          narration: 'In the stem, old xylem holds resins and gums.',
          caption: 'Old xylem → resins and gums → stored',
          heading: { title: 'Stored in the stem', text: 'Resins and gums', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem] },
          a11y: 'A second window opens beside the stem, showing resin and gum in the old xylem.',
        },
        {
          id: 'whole.soil',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.92, compose: 'right' },
          narration: 'Below ground, some wastes are excreted into the soil.',
          caption: 'Roots → waste substances → soil',
          heading: { title: 'Excreted', text: 'Into the soil around the roots', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labels: [MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem, MAP.soil] },
          animation: [{ process: 'soil', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Wastes drift from the roots into the soil.',
        },
        {
          id: 'whole.answer',
          cameraTarget: { preset: 'finalWide', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'So a plant has no single excretory organ, yet it still deals with its wastes. Some leave as a gas or as vapour, many are stored, some fall away with leaves, and some go into the soil.',
          caption: ['No single excretory organ, but many ways.', 'Released · stored · shed with leaves · into the soil.'],
          heading: { title: 'No single organ. Many ways.', appearAtMs: 1200 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labelsMax: 6, labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem, MAP.soil] },
          duration: { tailMs: 2000 },
          a11y: 'The whole plant with all six routes for its wastes labelled together.',
        },
      ],
    },

    // ================================================================== 05
    {
      id: 'recall',
      number: '05',
      title: 'Recall',
      shots: [
        {
          id: 'recall.open',
          cameraTarget: { preset: 'plantWide', transitionMs: 2000, endScale: 0.97, compose: 'right' },
          narration: 'Now it is your turn to remember. Answer from what you have seen, then explain it in your own words.',
          caption: ['Your turn to remember.', 'Then explain it in your own words.'],
          heading: { eyebrow: 'Your turn', title: 'What do you remember?', appearAtMs: 600 },
          view: { stage: 'plant' },
          interaction: { kind: 'recall' },
          a11y: 'The whole plant. The recall questions open.',
        },
      ],
    },
  ],
};

/** The synthesis map: one label per route, added one at a time in chapter 04. */
function MAP_LABELS() {
  return {
    oxygen: { anchor: 'ANCHOR_Leaf_Hero_Normal', text: 'Oxygen', sub: 'leaf → air', dir: 'left' },
    water: { anchor: 'ANCHOR_Canopy_Top', text: 'Excess water', sub: 'leaf → air', dir: 'right' },
    vacuole: { anchor: 'Leaf_Hero', text: 'Vacuoles', sub: 'wastes stored in cells', dir: 'left', inset: 'cell' },
    leaf: { anchor: 'Leaf_Old', text: 'Falling leaves', sub: 'stored wastes lost', dir: 'right' },
    xylem: { anchor: 'ANCHOR_Stem_Cut', text: 'Resins and gums', sub: 'stored in old xylem', dir: 'left', inset: 'stem' },
    soil: { anchor: 'ANCHOR_Root_Zone', text: 'Into the soil', sub: 'roots → soil', dir: 'right' },
  };
}
