/**
 * EXCRETION IN PLANTS: the lesson (Class 10 · NCERT §5.5.2), V2
 *
 * BASIC IDEA (01) → QUESTION (01) → PROBLEM (02) → DISCOVERY / PROCESS / EXPLANATION /
 * INTERACTION (03: eight places, followed one at a time) → SUMMARY (04) → RECALL (05)
 *
 * V2 follows every substance across SCALES, each with its own model:
 *   plant → leaf → inside the leaf → chloroplast → stoma → and back       (oxygen, CO2, water)
 *   plant → root → root hairs in the soil                                  (water in, wastes out)
 *   plant → leaf tissue → cell → vacuole → and back                        (stored wastes)
 *   plant → stem → stem slice → xylem → old xylem                          (resins and gums)
 * Sections are named by WHERE the camera goes, never by the answer.
 *
 * SHOT FIELDS
 *   id               stable id: narration clip, QA and audit key
 *   section          (chapter 03) which part of the journey
 *   cameraTarget     { preset, from, transitionMs, endScale, compose, follow }   presets: shots.js
 *   narration        what the teacher says (Google TTS clip per shot)
 *   caption          the concise on-screen idea: one line per spoken sentence (or one line for the shot)
 *   heading          topic heading, top-left: { eyebrow, title, text, appearAtMs } (never read aloud word for word)
 *   highlightObjects scene nodes lifted with the warm highlight
 *   view             { stage, soil:'shell', dim, night, labels:[≤5], veil:'in'|'out'|'inout', insets }
 *                    stage = which scale-specific model is shown (world.js STAGE_ASSETS)
 *   animation        processes started on this shot: { process, mode, through: shotId|'END' }
 *   interaction      a "Your turn" (the film waits for it)
 *   duration         { minMs, tailMs }; otherwise the shot lasts as long as its narration
 *   a11y             plain description of the frame for screen readers
 *
 * Every string here is original teaching text checked against the NCERT pages in /ncert
 * (docs/ncert-content-audit.md, docs/biological-accuracy-audit.md). Processes are pure
 * functions of lesson time, so the film can be paused, scrubbed or replayed anywhere.
 */

const FOLLOW = 'Follow the waste';
// V2.1: one location hierarchy for every heading eyebrow (Explore titles use the same names)
//   Plant › Leaf › Inside the leaf · Leaf surface › Stoma · Cell › Chloroplast / Vacuole
//   Plant › Stem › Cross-section › Xylem › Old xylem
//   Plant › Root › Root hairs › Soil
const PLANT = 'Plant';
const LEAF_PATH = 'Plant › Leaf';
const INSIDE_PATH = 'Plant › Leaf › Inside the leaf';
const CP_PATH = 'Plant › Leaf › Cell › Chloroplast';
const STOMA_PATH = 'Plant › Leaf › Leaf surface › Stoma';
const CELL_PATH = 'Plant › Leaf › Cell';
const VAC_PATH = 'Plant › Leaf › Cell › Vacuole';
const STEM_PATH = 'Plant › Stem';
const SECTION_PATH = 'Plant › Stem › Cross-section';
const XYLEM_PATH = 'Plant › Stem › Cross-section › Xylem';
const OLDX_PATH = 'Plant › Stem › Cross-section › Xylem › Old xylem';
const ROOT_PATH = 'Plant › Root';
const HAIR_PATH = 'Plant › Root › Root hairs';
const SOIL_PATH = 'Plant › Root › Root hairs › Soil';
const MAP = MAP_LABELS();

export const LESSON = {
  id: 'excretion-in-plants',
  version: 2,
  title: 'Excretion in Plants',
  subtitle: 'Class 10 Biology',
  thesis: 'A plant has no organ like a kidney. So where does its waste go?',
  centralQuestion: 'Plants do not have one specialised excretory organ like animals. So how do plants deal with their wastes?',

  chapters: [
    // ================================================================== 01
    {
      id: 'what',
      number: '01',
      title: 'What is excretion?',
      shots: [
        {
          id: 'what.alive',
          cameraTarget: { preset: 'plantIntro', transitionMs: 0, endScale: 0.9, compose: 'right' },
          narration: 'This plant is alive. Like every living thing, it has to keep working just to stay alive.',
          caption: ['This plant is alive.', 'It keeps working to stay alive.'],
          heading: { title: 'A living plant', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'A young green plant standing in a block of soil.',
        },
        {
          id: 'what.processes',
          cameraTarget: { preset: 'plantWide', transitionMs: 2600, endScale: 0.94, compose: 'right' },
          narration: 'The jobs that keep it alive are called life processes. A plant makes its own food, and breaks food down to get energy.',
          caption: ['Jobs that keep it alive: life processes.', 'It makes food, and gets energy from it.'],
          heading: { title: 'Staying alive', text: 'Life processes: making food, getting energy', appearAtMs: 700 },
          view: { stage: 'plant' },
          a11y: 'The whole plant, slowly turning.',
        },
        {
          id: 'what.byproducts',
          cameraTarget: { preset: 'plantCanopy', transitionMs: 2200, endScale: 0.9, compose: 'right' },
          narration: 'But life processes also make substances the plant does not need. Some of them could even harm it if they stayed.',
          caption: ['Life processes also make unwanted substances.', 'Some could even be harmful.'],
          heading: { title: 'Substances it does not need', appearAtMs: 900 },
          view: { stage: 'plant' },
          animation: [{ process: 'intro', mode: 'wastes', through: 'what.question' }],
          duration: { minMs: 8500 },
          a11y: 'Small purple particles, the unwanted substances, appear inside the leaves and stem.',
        },
        {
          id: 'what.excretion',
          cameraTarget: { preset: 'plantCanopy', transitionMs: 1200, endScale: 0.82, compose: 'right' },
          narration: 'Removing these harmful wastes from the body is called excretion. Every living thing has to do it in some way.',
          caption: ['Removing harmful wastes: excretion.', 'Every living thing must do it.'],
          heading: { title: 'Excretion', text: 'Getting rid of harmful wastes', appearAtMs: 700 },
          view: { stage: 'plant' },
          a11y: 'The purple waste particles glow inside the plant.',
        },
        {
          id: 'what.question',
          cameraTarget: { preset: 'plantWide', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'Plants also carry out life processes. So what happens to the substances they do not need?',
          caption: ['Plants carry out life processes too.', 'So where do their unwanted substances go?'],
          heading: { title: 'What happens to a plant’s wastes?', appearAtMs: 900 },
          view: { stage: 'plant' },
          duration: { tailMs: 1600 },
          a11y: 'The whole plant, with its wastes inside.',
        },
      ],
    },

    // ================================================================== 02
    {
      id: 'different',
      number: '02',
      title: 'Why is plant excretion different?',
      shots: [
        {
          id: 'different.animals',
          cameraTarget: { preset: 'plantWide', transitionMs: 1400, endScale: 0.96, compose: 'right' },
          narration: 'Many animals, like us, have special organs for this job. Our two kidneys filter wastes out of the blood.',
          caption: ['Animals have special organs for excretion.', 'Our kidneys filter wastes from the blood.'],
          heading: { title: 'Animals use special organs', appearAtMs: 700 },
          view: { stage: 'plant' },
          animation: [{ process: 'figure', mode: 'kidneys', through: 'different.none' }],
          a11y: 'A small drawing of a human body with the two kidneys marked, beside the plant.',
        },
        {
          id: 'different.parts',
          cameraTarget: { preset: 'plantFront', transitionMs: 2200, endScale: 0.95, compose: 'right' },
          narration: 'Now look at the plant. It has leaves, a stem with branches, and roots in the soil.',
          caption: 'Leaves, a stem with branches, and roots.',
          heading: { title: 'Leaves, stem, roots', appearAtMs: 700 },
          view: {
            stage: 'plant',
            soil: 'shell',
            labels: [
              { anchor: 'Leaf_Hero', text: 'Leaves', dir: 'left', atMs: 1600 },
              { anchor: 'ANCHOR_Plant_Center', text: 'Stem and branches', dir: 'right', atMs: 3000 },
              { anchor: 'ANCHOR_Root_Zone', text: 'Roots', dir: 'right', atMs: 4600 },
            ],
          },
          animation: [{ process: 'partsTour' }],
          duration: { minMs: 8000 },
          a11y: 'The soil turns see-through. The leaves, then the stem and branches, then the roots light up in turn.',
        },
        {
          id: 'different.none',
          cameraTarget: { preset: 'plantWide', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'But none of these parts works like a kidney. Plants use completely different ways to deal with their wastes.',
          caption: ['No part works like a kidney.', 'Plants use completely different ways.'],
          heading: { title: 'No organ like a kidney', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant again, with no part lit up.',
        },
        {
          id: 'different.question',
          cameraTarget: { preset: 'plantQuestion', transitionMs: 2200, endScale: 0.9, compose: 'right' },
          narration: 'So here is our big question. If a plant has no special excretory organ, what does it do with its wastes?',
          caption: ['Our big question:', 'No excretory organ… so what happens to its wastes?'],
          heading: { eyebrow: 'The big question', title: 'So how does a plant deal with its wastes?', appearAtMs: 600 },
          view: { stage: 'plant' },
          duration: { tailMs: 2800 },
          a11y: 'A slow move towards the plant while the question stays on screen.',
        },
        {
          id: 'different.plan',
          cameraTarget: { preset: 'plantWide', transitionMs: 1800, endScale: 0.94, compose: 'right' },
          narration: 'Let’s find out. We will follow the waste through the plant, one place at a time, starting high up at a leaf.',
          caption: 'We’ll follow the waste, place by place.',
          heading: { title: 'Where does the waste go?', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
      ],
    },

    // ================================================================== 03
    {
      id: 'follow',
      number: '03',
      title: FOLLOW,
      sections: [
        { id: 'oxygen', title: 'A leaf by day' },
        { id: 'stoma', title: 'A tiny pore' },
        { id: 'night', title: 'At night' },
        { id: 'water', title: 'Water in the plant' },
        { id: 'vacuole', title: 'Inside a cell' },
        { id: 'leaves', title: 'An older leaf' },
        { id: 'resin', title: 'Inside the stem' },
        { id: 'soil', title: 'Around the roots' },
      ],
      shots: [
        // ---------------------------------------------------------- a. a leaf by day (oxygen)
        {
          id: 'oxygen.travel',
          section: 'oxygen',
          cameraTarget: { preset: 'leafApproach', transitionMs: 3200, endScale: 0.94, compose: 'right' },
          narration: 'Our first stop is a leaf, high up on the plant.',
          caption: 'First stop: a leaf.',
          heading: { eyebrow: LEAF_PATH, title: 'Start at a leaf', appearAtMs: 2200 },
          view: { stage: 'plant' },
          a11y: 'The camera rises through the plant to one large leaf.',
        },
        {
          id: 'oxygen.look',
          section: 'oxygen',
          cameraTarget: { preset: 'leafHero', transitionMs: 1800, endScale: 0.94, compose: 'right' },
          narration: 'Leaves make the plant’s food. They do it by a process called photosynthesis.',
          caption: ['Leaves make the plant’s food…', '…by photosynthesis.'],
          heading: { eyebrow: LEAF_PATH, title: 'Where food is made', appearAtMs: 700 },
          view: { stage: 'plant', veil: 'in' },
          a11y: 'A close view of one leaf with its veins.',
        },
        {
          id: 'oxygen.leaf',
          section: 'oxygen',
          cameraTarget: { preset: 'leaf2', from: 'leaf2Far', transitionMs: 2800, endScale: 0.94, compose: 'right' },
          narration: 'Let’s look much closer at one leaf, and then inside it.',
          caption: 'Closer: one leaf, then inside it.',
          heading: { eyebrow: LEAF_PATH, title: 'One leaf, magnified', appearAtMs: 1200 },
          view: { stage: 'leaf', veil: 'inout' },
          duration: { minMs: 5600 },
          a11y: 'One green leaf fills the screen: its blade, veins and stalk.',
        },
        {
          id: 'oxygen.inside',
          section: 'oxygen',
          cameraTarget: { preset: 'liWide', from: 'liFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'Here the leaf is cut open. It is made of layers of cells, with air spaces between them.',
          caption: ['The leaf, cut open.', 'Layers of cells, with air spaces between them.'],
          heading: { eyebrow: INSIDE_PATH, title: 'Inside a leaf', appearAtMs: 1600 },
          view: {
            stage: 'leafInternal',
            veil: 'out',
            labels: [
              { anchor: 'ANCHOR_LI_Palisade', text: 'Cells', dir: 'left', atMs: 2600 },
              { anchor: 'ANCHOR_LI_Air_Space', text: 'Air spaces', dir: 'right', atMs: 4200 },
            ],
          },
          a11y: 'A slice through a leaf: rows of green cells, with dark air spaces between the rounder cells lower down.',
        },
        {
          id: 'oxygen.chloroplast',
          section: 'oxygen',
          cameraTarget: { preset: 'liPalisade', transitionMs: 2200, endScale: 0.94, compose: 'right' },
          narration: 'These cells hold many small green bodies called chloroplasts. They contain chlorophyll, which photosynthesis needs.',
          caption: ['Green bodies in the cells: chloroplasts.', 'They contain chlorophyll, needed for photosynthesis.'],
          heading: { eyebrow: INSIDE_PATH, title: 'Chloroplasts', appearAtMs: 900 },
          view: { stage: 'leafInternal', veil: 'in', labels: [{ anchor: 'ANCHOR_LI_Chloroplast', text: 'Chloroplasts', dir: 'right' }] },
          a11y: 'Tall cells packed with small green chloroplasts, which glow gently.',
        },
        {
          id: 'oxygen.photo',
          section: 'oxygen',
          cameraTarget: { preset: 'chloroplast', from: 'chloroplastFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'In sunlight, chloroplasts help the leaf use carbon dioxide and water to make food.',
          caption: 'Sunlight: carbon dioxide + water → food.',
          heading: { eyebrow: CP_PATH, title: 'Photosynthesis', text: 'Sunlight, carbon dioxide and water make food', appearAtMs: 1400 },
          view: {
            stage: 'chloroplast',
            veil: 'out',
            labels: [
              { anchor: 'TRACK_CP_CO2', text: 'Carbon dioxide', dir: 'left', atMs: 1300 },
              { anchor: 'TRACK_CP_Water', text: 'Water', dir: 'right', atMs: 1700 },
              { anchor: 'ANCHOR_CP_Discs', text: 'Discs with chlorophyll', dir: 'right', atMs: 5200 },
            ],
          },
          animation: [{ process: 'photosynthesis', mode: 'light' }],
          duration: { minMs: 7500 },
          a11y: 'One chloroplast, cut open. Sunlight falls on it; its stacks of green discs glow as carbon dioxide and water drift in.',
        },
        {
          id: 'oxygen.produce',
          section: 'oxygen',
          cameraTarget: { preset: 'chloroplastClose', transitionMs: 2000, endScale: 0.92, compose: 'right' },
          narration: 'Photosynthesis also makes a gas: oxygen. Watch it form.',
          caption: ['Photosynthesis also makes oxygen.', 'Watch it form.'],
          heading: { eyebrow: CP_PATH, title: 'Something else is made', appearAtMs: 1400 },
          view: { stage: 'chloroplast', veil: 'in', labels: [{ anchor: 'TRACK_CP_O2', text: 'Oxygen', dir: 'right', atMs: 2400 }] },
          animation: [{ process: 'photosynthesis', mode: 'form' }],
          duration: { minMs: 7000 },
          a11y: 'Small pairs of pale blue spheres, oxygen, form among the green discs.',
        },
        {
          id: 'oxygen.path',
          section: 'oxygen',
          cameraTarget: { preset: 'liStoma', from: 'liWide', transitionMs: 3200, endScale: 0.95, compose: 'right' },
          narration: 'The oxygen leaves the cells and spreads through the air spaces. It reaches a tiny pore in the leaf’s surface.',
          caption: ['Out of the cells, through the air spaces…', '…to a tiny pore in the leaf’s surface.'],
          heading: { eyebrow: INSIDE_PATH, title: 'The way out', appearAtMs: 1400 },
          view: {
            stage: 'leafInternal',
            veil: 'inout',
            labels: [
              { anchor: 'ANCHOR_LI_Air_Space', text: 'Air space', dir: 'left', atMs: 2600 },
              { anchor: 'ANCHOR_LI_Stoma', text: 'A tiny pore', dir: 'right', atMs: 5200 },
            ],
          },
          animation: [{ process: 'leafInside', mode: 'o2' }],
          duration: { minMs: 8500 },
          a11y: 'Oxygen moves from the green cells down through the air spaces to a gap in the lower surface of the leaf.',
        },
        {
          id: 'oxygen.release',
          section: 'oxygen',
          cameraTarget: { preset: 'stoma', from: 'stomaFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'This tiny pore is called a stoma. Through it, the oxygen passes out into the air.',
          caption: ['This pore is a stoma.', 'Oxygen passes out through it, into the air.'],
          heading: { eyebrow: STOMA_PATH, title: 'Out through a stoma', appearAtMs: 1400 },
          view: { stage: 'stoma', veil: 'inout', labels: [{ anchor: 'ANCHOR_Stoma_Pore', text: 'Stoma', dir: 'right', atMs: 1600 }] },
          animation: [{ process: 'stomaGas', mode: 'o2' }],
          duration: { minMs: 7500 },
          a11y: 'The surface of the leaf, magnified: a pore between two bean-shaped cells. Oxygen rises out of the pore.',
        },
        {
          id: 'oxygen.reason',
          section: 'oxygen',
          cameraTarget: { preset: 'leafAir', from: 'leafDive', transitionMs: 3000, endScale: 0.9, compose: 'right' },
          narration: 'The plant makes this oxygen and then gives it out. So oxygen can be thought of as a waste product of photosynthesis, and the plant gets rid of it by releasing it into the air.',
          caption: ['Made, then given out.', 'Oxygen: a waste product, released into the air.'],
          heading: { eyebrow: LEAF_PATH, title: 'Oxygen as waste', appearAtMs: 1600 },
          view: { stage: 'plant', veil: 'out' },
          animation: [{ process: 'sunlight' }, { process: 'oxygen', mode: 'release' }],
          a11y: 'Back at the whole leaf: oxygen keeps rising from it into the air.',
        },
        {
          id: 'oxygen.try',
          section: 'oxygen',
          cameraTarget: { preset: 'leafAir', transitionMs: 900, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. Bring the sunlight to the leaf, and watch what comes out of it.',
          caption: 'Your turn: bring sunlight to the leaf.',
          heading: { eyebrow: 'Your turn', title: 'Sunlight on the leaf', appearAtMs: 500 },
          view: { stage: 'plant' },
          interaction: {
            kind: 'sunlight',
            task: 'Drag the slider to bring sunlight to the leaf.',
            done: 'With sunlight, the leaf makes food, and oxygen leaves it.',
          },
          a11y: 'A slider controls the sunlight falling on the leaf.',
        },

        // ---------------------------------------------------------- b. a tiny pore (stomata, guard cells)
        {
          id: 'stoma.look',
          section: 'stoma',
          cameraTarget: { preset: 'stomaTop', from: 'stomaFar', transitionMs: 3200, endScale: 0.95, compose: 'right' },
          narration: 'The oxygen left through a stoma. A leaf has many of these tiny pores, called stomata. Each one has two guard cells around it, and this one is closed.',
          caption: ['The oxygen left through a stoma.', 'A leaf has many tiny pores: stomata.', 'Two guard cells around each; this one is closed.'],
          heading: { eyebrow: STOMA_PATH, title: 'Stomata and guard cells', appearAtMs: 1400 },
          highlightObjects: ['Guard_Cell_L', 'Guard_Cell_R'],
          view: {
            stage: 'stoma',
            veil: 'out',
            labels: [
              { anchor: 'ANCHOR_Guard_Cell_L', text: 'Guard cell', dir: 'left', atMs: 3600 },
              { anchor: 'ANCHOR_Guard_Cell_R', text: 'Guard cell', dir: 'right', atMs: 3600 },
            ],
          },
          animation: [{ process: 'stoma', mode: 'shut' }],
          a11y: 'Looking down on one stoma: a closed slit between two curved guard cells, with more stomata further away.',
        },
        {
          id: 'stoma.open',
          section: 'stoma',
          cameraTarget: { preset: 'stomaTop', transitionMs: 600, endScale: 0.9, compose: 'right' },
          narration: 'When water flows into the guard cells, they swell and curve apart, and the pore between them opens.',
          caption: 'Water flows in: guard cells swell and curve apart; the pore opens.',
          heading: { eyebrow: STOMA_PATH, title: 'Opening', appearAtMs: 900 },
          view: { stage: 'stoma', labels: [{ anchor: 'ANCHOR_Stoma_Pore', text: 'Pore opens', dir: 'right', atMs: 3200 }] },
          animation: [{ process: 'stoma', mode: 'open' }],
          duration: { minMs: 6500 },
          a11y: 'Blue water drops move into both guard cells; they swell and bow apart, and the pore between them opens.',
        },
        {
          id: 'stoma.reason',
          section: 'stoma',
          cameraTarget: { preset: 'stoma', transitionMs: 1800, endScale: 0.94, compose: 'right' },
          narration: 'Open stomata let gases pass in and out of the leaf. That is how the oxygen got out. But a lot of water can also be lost through them.',
          caption: ['Open stomata: gases pass in and out.', 'That is how the oxygen got out.', 'But a lot of water can be lost too.'],
          heading: { eyebrow: STOMA_PATH, title: 'What passes through', appearAtMs: 1200 },
          view: { stage: 'stoma', labels: [{ anchor: 'TRACK_STOMA_O2', text: 'Oxygen', dir: 'left', atMs: 1200 }, { anchor: 'TRACK_STOMA_Vapour', text: 'Water vapour', dir: 'right', atMs: 6000 }] },
          animation: [{ process: 'stomaGas', mode: 'o2vapour' }],
          duration: { minMs: 7000 },
          a11y: 'The open stoma: oxygen passes out through the pore, then soft white puffs of water vapour escape too.',
        },
        {
          id: 'stoma.close',
          section: 'stoma',
          cameraTarget: { preset: 'stomaTop', transitionMs: 600, endScale: 0.95, compose: 'right' },
          narration: 'When the guard cells shrink, the pore closes. Closing its stomata keeps the plant from losing too much water.',
          caption: ['Guard cells shrink: the pore closes.', 'Closing stomata saves water.'],
          heading: { eyebrow: STOMA_PATH, title: 'Closing', appearAtMs: 900 },
          view: { stage: 'stoma' },
          animation: [{ process: 'stoma', mode: 'close' }],
          duration: { minMs: 6500 },
          a11y: 'Water drops leave the guard cells; they shrink and the pore closes to a slit.',
        },
        {
          id: 'stoma.try',
          section: 'stoma',
          cameraTarget: { preset: 'stomaTop', transitionMs: 900, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. Let water flow into the guard cells, and watch the pore.',
          caption: 'Your turn: let water into the guard cells.',
          heading: { eyebrow: 'Your turn', title: 'Open the stoma', appearAtMs: 500 },
          view: { stage: 'stoma' },
          animation: [{ process: 'stoma', mode: 'shut' }],
          interaction: {
            kind: 'guardCells',
            task: 'Drag the slider to let water flow into the guard cells.',
            done: 'The guard cells swell with water, and the pore opens.',
          },
          a11y: 'A slider sets how much water is in the guard cells; the pore opens as they fill.',
        },
        {
          id: 'stoma.other',
          section: 'stoma',
          cameraTarget: { preset: 'plantSurfaces', from: 'plantWide', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'Stomata are not the only way. Gases are also exchanged across the surface of stems and roots.',
          caption: ['Not only through stomata:', 'gases also cross the surface of stems and roots.'],
          heading: { eyebrow: PLANT, title: 'Stems and roots too', appearAtMs: 1600 },
          view: { stage: 'plant', soil: 'shell', veil: 'out' },
          animation: [{ process: 'surfaceGas' }],
          duration: { minMs: 7000 },
          a11y: 'The whole plant with see-through soil. Tiny gas particles cross the surface of the stem and the roots.',
        },

        // ---------------------------------------------------------- c. at night (carbon dioxide)
        {
          id: 'night.respire',
          section: 'night',
          cameraTarget: { preset: 'plantNight', transitionMs: 2200, endScale: 0.94, compose: 'right' },
          narration: 'Now follow a second gas. Plant cells also respire, by day and by night. Respiration makes carbon dioxide, and this carbon dioxide is a gaseous waste.',
          caption: ['Now follow a second gas.', 'Plant cells respire, day and night.', 'Respiration makes carbon dioxide: a gaseous waste.'],
          heading: { eyebrow: PLANT, title: 'A waste of respiration', text: 'Carbon dioxide', appearAtMs: 900 },
          view: { stage: 'plant', veil: 'in', labels: [{ anchor: 'TRACK_RESP_CO2', text: 'Carbon dioxide', dir: 'right', atMs: 6300 }] },
          animation: [{ process: 'nightCO2', mode: 'form' }],
          a11y: 'The whole plant in daylight. Grey carbon dioxide appears in its leaves as the cells respire.',
        },
        {
          id: 'night.night',
          section: 'night',
          cameraTarget: { preset: 'liStoma', from: 'liFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'At night there is no photosynthesis. Then getting rid of carbon dioxide is the main gas exchange going on.',
          caption: ['At night: no photosynthesis.', 'Getting rid of carbon dioxide is the main exchange.'],
          heading: { eyebrow: INSIDE_PATH, title: 'Given out at night', appearAtMs: 1200 },
          view: { stage: 'leafInternal', night: true, veil: 'out' },
          animation: [{ process: 'leafInside', mode: 'co2night' }],
          duration: { minMs: 8500 },
          a11y: 'The light dims to night. Carbon dioxide from the cells moves through the air spaces and slowly out of the leaf.',
        },
        {
          id: 'night.day',
          section: 'night',
          cameraTarget: { preset: 'liWide', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'By day, this carbon dioxide is used up in photosynthesis, so the leaf does not give it out. Oxygen is what leaves.',
          caption: ['By day: this carbon dioxide is used in photosynthesis.', 'Oxygen is what leaves.'],
          heading: { eyebrow: INSIDE_PATH, title: 'Used by day', appearAtMs: 1600 },
          view: { stage: 'leafInternal', veil: 'in' },
          animation: [{ process: 'leafInside', mode: 'co2day' }],
          duration: { minMs: 8000 },
          a11y: 'Day returns inside the leaf: grey carbon dioxide from the cells moves to the green chloroplasts and is used up, while oxygen leaves.',
        },
        {
          id: 'night.reason',
          section: 'night',
          cameraTarget: { preset: 'plantNight', from: 'leafDive', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'So carbon dioxide from respiration is a waste, and at night the plant gives it out into the air. By day, the same gas is used instead, as an input for photosynthesis.',
          caption: ['CO₂ from respiration: a waste, given out at night.', 'By day: an input for photosynthesis instead.'],
          heading: { eyebrow: PLANT, title: 'Waste, or input?', text: 'Night: given out · Day: used', appearAtMs: 1400 },
          view: { stage: 'plant', night: true, veil: 'out' },
          animation: [{ process: 'nightCO2' }],
          a11y: 'The whole plant at night; grey carbon dioxide drifts slowly away from its leaves.',
        },

        // ---------------------------------------------------------- d. water (transpiration)
        {
          id: 'water.question',
          section: 'water',
          cameraTarget: { preset: 'leafHero', transitionMs: 1600, endScale: 0.95, compose: 'right' },
          narration: 'A plant also takes in a lot of water, often more than it needs. What happens to the extra water?',
          caption: ['Plants take in lots of water.', 'What happens to the extra?'],
          heading: { eyebrow: LEAF_PATH, title: 'Too much water?', appearAtMs: 800 },
          view: { stage: 'plant' },
          duration: { tailMs: 1000 },
          a11y: 'The leaf again, in daylight.',
        },
        {
          id: 'water.enter',
          section: 'water',
          cameraTarget: { preset: 'waterRoots', transitionMs: 3400, endScale: 0.94, compose: 'right' },
          narration: 'Water from the soil enters the plant through its roots.',
          caption: 'Water enters through the roots.',
          heading: { eyebrow: ROOT_PATH, title: 'In at the roots', appearAtMs: 2400 },
          view: { stage: 'plant', soil: 'shell', veil: 'in' },
          animation: [{ process: 'water', mode: 'enter' }],
          duration: { minMs: 7500 },
          a11y: 'The soil becomes see-through. Blue drops of water move from the soil into a root.',
        },
        {
          id: 'water.hairs',
          section: 'water',
          cameraTarget: { preset: 'rootHairsMicro', from: 'rootHairsFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'Up close, the root has tiny root hairs. They give it a large surface for taking in water from the soil.',
          caption: ['Up close: tiny root hairs.', 'A large surface for taking in water.'],
          heading: { eyebrow: HAIR_PATH, title: 'Hairs on the root', appearAtMs: 1400 },
          view: {
            stage: 'rootHairs',
            veil: 'inout',
            labels: [
              { anchor: 'ANCHOR_RH_Hair', text: 'Root hair', dir: 'right', atMs: 2200 },
              { anchor: 'ANCHOR_RH_Soil_Water', text: 'Water in the soil', dir: 'left', atMs: 4200 },
            ],
          },
          animation: [{ process: 'hairFlow', mode: 'water' }],
          duration: { minMs: 8000 },
          a11y: 'Long thin root hairs grow out of the root’s surface cells between brown soil particles. Water moves from the soil into a hair.',
        },
        {
          id: 'water.root',
          section: 'water',
          cameraTarget: { preset: 'rootSection', from: 'rootHairZone', transitionMs: 3400, endScale: 0.95, compose: 'right' },
          narration: 'The water moves on into the root, and into its tubes called xylem.',
          caption: 'Into the root, and into its xylem tubes.',
          heading: { eyebrow: ROOT_PATH, title: 'To the xylem', appearAtMs: 1600 },
          view: { stage: 'root', veil: 'inout', labels: [{ anchor: 'ANCHOR_RT_Xylem', text: 'Xylem', dir: 'right', atMs: 3600 }] },
          animation: [{ process: 'rootFlow', mode: 'water' }],
          duration: { minMs: 7500 },
          a11y: 'One root, magnified and cut open at the top. Water drops pass from the root hairs into the root and up its central strand, the xylem.',
        },
        {
          id: 'water.rise',
          section: 'water',
          cameraTarget: { preset: 'waterRoots', transitionMs: 1200, follow: { process: 'water', target: 'lead' }, compose: 'center' },
          narration: 'Through the xylem, it rises up the stem and out along the branches to the leaves.',
          caption: 'Up the stem in the xylem, out to the leaves.',
          heading: { eyebrow: STEM_PATH, title: 'Up through the plant', appearAtMs: 900 },
          view: { stage: 'plant', soil: 'shell', veil: 'inout' },
          animation: [{ process: 'water', mode: 'rise' }],
          duration: { minMs: 9500 },
          a11y: 'The camera follows a drop of water as it climbs up inside the stem to a leaf.',
        },
        {
          id: 'water.leaf',
          section: 'water',
          cameraTarget: { preset: 'liVein', from: 'liFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'In the leaf, water passes out of the xylem, into the cells around it.',
          caption: 'Out of the leaf’s xylem, into its cells.',
          heading: { eyebrow: INSIDE_PATH, title: 'Into the leaf’s cells', appearAtMs: 1400 },
          view: { stage: 'leafInternal', veil: 'out', labels: [{ anchor: 'ANCHOR_LI_Xylem', text: 'Xylem', dir: 'right', atMs: 1800 }] },
          animation: [{ process: 'leafInside', mode: 'water', through: 'water.vapour' }],
          duration: { minMs: 7000 },
          a11y: 'Inside the leaf: a vein with its xylem. Blue water drops leave the xylem towards the cells.',
        },
        {
          id: 'water.vapour',
          section: 'water',
          cameraTarget: { preset: 'liStoma', transitionMs: 2400, endScale: 0.95, compose: 'right' },
          narration: 'From the cells, some water evaporates into the air spaces, as water vapour.',
          caption: 'Water evaporates into the air spaces, as vapour.',
          heading: { eyebrow: INSIDE_PATH, title: 'Water becomes vapour', appearAtMs: 1200 },
          view: { stage: 'leafInternal', veil: 'in', labels: [{ anchor: 'TRACK_LI_Vapour', text: 'Water vapour', dir: 'left', atMs: 2400 }] },
          duration: { minMs: 7000 },
          a11y: 'The drops turn into soft white puffs of vapour in the air space above the pore.',
        },
        {
          id: 'water.out',
          section: 'water',
          cameraTarget: { preset: 'stoma', from: 'stomaFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'The water vapour escapes through the stomata, into the air.',
          caption: 'Vapour escapes through the stomata.',
          heading: { eyebrow: STOMA_PATH, title: 'Out as vapour', appearAtMs: 1200 },
          view: { stage: 'stoma', veil: 'inout' },
          animation: [{ process: 'stomaGas', mode: 'vapour' }],
          duration: { minMs: 6500 },
          a11y: 'Puffs of water vapour rise out of the open stoma.',
        },
        {
          id: 'water.reason',
          section: 'water',
          cameraTarget: { preset: 'waterWide', from: 'leafDive', transitionMs: 3200, endScale: 0.95, compose: 'right' },
          narration: 'Losing water as vapour like this is called transpiration. It is how a plant gets rid of its excess water.',
          caption: ['Losing water as vapour: transpiration.', 'It gets rid of excess water.'],
          heading: { eyebrow: PLANT, title: 'Transpiration', text: 'Excess water leaves as vapour', appearAtMs: 1600 },
          view: { stage: 'plant', soil: 'shell', veil: 'out' },
          animation: [{ process: 'water', mode: 'cycle' }],
          a11y: 'The whole plant: water rises from the roots and vapour leaves the leaves.',
        },

        // ---------------------------------------------------------- e. inside a cell (vacuole)
        {
          id: 'vacuole.pivot',
          section: 'vacuole',
          cameraTarget: { preset: 'plantWide', transitionMs: 2200, endScale: 0.95, compose: 'right' },
          narration: 'Gases and extra water leave the plant. But some wastes are not removed at all. They are kept inside the plant.',
          caption: ['Gases and extra water leave the plant.', 'Some wastes are not removed…', '…they are kept inside.'],
          heading: { eyebrow: PLANT, title: 'Not every waste leaves', text: 'Remove, or store?', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
        {
          id: 'vacuole.dive',
          section: 'vacuole',
          cameraTarget: { preset: 'leafDive', transitionMs: 3200, compose: 'center' },
          narration: 'To see where, we need to zoom right into a leaf.',
          caption: 'Zooming into a leaf…',
          heading: { eyebrow: LEAF_PATH, title: 'Closer', appearAtMs: 600 },
          view: { stage: 'plant', veil: 'in' },
          duration: { minMs: 5200 },
          a11y: 'The camera moves right up to the surface of the leaf.',
        },
        {
          id: 'vacuole.tissue',
          section: 'vacuole',
          cameraTarget: { preset: 'liWide', from: 'liFar', transitionMs: 2600, endScale: 0.92, compose: 'right' },
          narration: 'Up close, a leaf is made of many tiny cells, packed together.',
          caption: 'A leaf is made of many tiny cells.',
          heading: { eyebrow: INSIDE_PATH, title: 'Many cells', appearAtMs: 1200 },
          view: { stage: 'leafInternal', veil: 'inout' },
          duration: { minMs: 6500 },
          a11y: 'A magnified slice of leaf: layers of green cells.',
        },
        {
          id: 'vacuole.cell',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', from: 'cellFar', transitionMs: 3000, endScale: 0.94, compose: 'right' },
          narration: 'Here is one of those cells, opened up. It has a cell wall, jelly-like cytoplasm, a nucleus, and one large vacuole.',
          caption: ['One plant cell, opened up.', 'Wall, cytoplasm, nucleus, one large vacuole.'],
          heading: { eyebrow: CELL_PATH, title: 'One plant cell', appearAtMs: 2200 },
          view: {
            stage: 'cell',
            veil: 'out',
            labels: [
              { anchor: 'ANCHOR_Cell_Wall', text: 'Cell wall', dir: 'right' },
              { anchor: 'ANCHOR_Cytoplasm', text: 'Cytoplasm', dir: 'left' },
              { anchor: 'ANCHOR_Nucleus', text: 'Nucleus', dir: 'left' },
              { anchor: 'ANCHOR_Vacuole_Front', text: 'Vacuole', dir: 'right' },
            ],
          },
          a11y: 'One cell cut open, showing its wall, cytoplasm, nucleus and a large vacuole.',
        },
        {
          id: 'vacuole.store',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', transitionMs: 600, endScale: 0.86, compose: 'right' },
          narration: 'Now watch the wastes in the cytoplasm. They move into the vacuole, and there they stay.',
          caption: ['Watch the wastes…', '…they move into the vacuole and stay.'],
          heading: { eyebrow: CELL_PATH, title: 'Where the wastes go', appearAtMs: 1800 },
          view: { stage: 'cell' },
          animation: [{ process: 'vacuole', mode: 'store', through: 'END' }],
          duration: { minMs: 9000 },
          a11y: 'Purple waste particles drift into the vacuole and stay there.',
        },
        {
          id: 'vacuole.reason',
          section: 'vacuole',
          cameraTarget: { preset: 'vacuole', transitionMs: 2000, endScale: 0.94, compose: 'right' },
          narration: 'The vacuole is a storage space inside the cell, with its own thin membrane around it. Many plant waste products are stored in vacuoles like this one. They are kept, not removed from the plant.',
          caption: ['The vacuole: a store, inside its own membrane.', 'Many plant wastes are stored in vacuoles.', 'Kept inside, not removed.'],
          heading: { eyebrow: VAC_PATH, title: 'Stored, not removed', appearAtMs: 900 },
          highlightObjects: ['Vacuole'],
          view: {
            stage: 'cell',
            labels: [
              { anchor: 'ANCHOR_Vacuole_Membrane', text: 'Vacuole membrane', dir: 'left', atMs: 1400 },
              { anchor: 'ANCHOR_Vacuole_Front', text: 'Stored wastes', dir: 'right', atMs: 4600 },
            ],
          },
          a11y: 'A close view of the vacuole, its thin membrane, and the wastes held inside it.',
        },
        {
          id: 'vacuole.try',
          section: 'vacuole',
          cameraTarget: { preset: 'cell', transitionMs: 1600, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. A few wastes are still in the cytoplasm. Move them into the vacuole.',
          caption: 'Your turn: store the last wastes.',
          heading: { eyebrow: 'Your turn', title: 'Store the wastes', appearAtMs: 500 },
          view: { stage: 'cell' },
          interaction: {
            kind: 'storeWaste',
            task: 'Tap each purple waste, or use the button, to move it into the vacuole.',
            done: 'Stored. The wastes stay inside the vacuole.',
          },
          a11y: 'Three wastes wait in the cytoplasm. Tapping one moves it into the vacuole.',
        },
        {
          id: 'vacuole.back',
          section: 'vacuole',
          cameraTarget: { preset: 'cellFar', transitionMs: 3000, compose: 'center' },
          narration: 'Now let’s pull back out: from the vacuole, to the cell, to the leaf.',
          caption: 'Vacuole → cell → leaf…',
          heading: { eyebrow: CELL_PATH, title: 'Pulling back', appearAtMs: 600 },
          view: {
            stage: 'cell',
            veil: 'in',
            // part-way through, the scale changes to the leaf model and the camera keeps pulling back
            then: { atMs: 3300, stage: 'leaf', cameraTarget: { preset: 'leaf2', from: 'leaf2Surface', transitionMs: 2600, compose: 'center' } },
          },
          duration: { minMs: 7800 },
          a11y: 'The camera pulls back from the vacuole to the whole cell, then out from the leaf’s surface to the whole leaf.',
        },
        {
          id: 'vacuole.plant',
          section: 'vacuole',
          cameraTarget: { preset: 'plantWide', from: 'leafDive', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'And back to the whole plant. Its leaves are made of cells like the one we just saw.',
          caption: ['…and back to the whole plant.', 'Its leaves are made of cells like that one.'],
          heading: { eyebrow: PLANT, title: 'The whole plant again', appearAtMs: 1800 },
          view: { stage: 'plant', veil: 'out' },
          a11y: 'The camera pulls back from the leaf surface to the whole plant.',
        },

        // ---------------------------------------------------------- f. an older leaf
        {
          id: 'leaves.lose',
          section: 'leaves',
          cameraTarget: { preset: 'plantWide', transitionMs: 1400, endScale: 0.94, compose: 'right' },
          narration: 'Plants have another useful ability. They can even lose some of their parts, such as leaves.',
          caption: ['Plants have another useful ability.', 'They can lose some parts, like leaves.'],
          heading: { eyebrow: PLANT, title: 'Losing parts', appearAtMs: 900 },
          view: { stage: 'plant' },
          a11y: 'The whole plant.',
        },
        {
          id: 'leaves.look',
          section: 'leaves',
          cameraTarget: { preset: 'leafOld', transitionMs: 2600, endScale: 0.94, compose: 'right' },
          narration: 'Look at this leaf, low down on the stem. It is one of the plant’s older leaves.',
          caption: 'An older leaf, low on the stem.',
          heading: { eyebrow: LEAF_PATH, title: 'Low on the stem', appearAtMs: 1600 },
          highlightObjects: ['Leaf_Old'],
          view: { stage: 'plant', labels: [{ anchor: 'Leaf_Old', text: 'An older leaf', dir: 'right' }] },
          a11y: 'A close view of an older leaf low on the stem.',
        },
        {
          id: 'leaves.load',
          section: 'leaves',
          cameraTarget: { preset: 'leafOld', transitionMs: 600, endScale: 0.88, compose: 'right' },
          narration: 'Some waste products are stored in leaves like this one. Time passes, and the leaf grows older.',
          caption: ['Some wastes are stored in the leaf.', 'Time passes…'],
          heading: { eyebrow: LEAF_PATH, title: 'Stored in the leaf', appearAtMs: 1600 },
          view: { stage: 'plant' },
          animation: [{ process: 'leafFall', through: 'END' }],
          duration: { minMs: 9000 },
          a11y: 'Purple wastes gather in the older leaf, which slowly turns yellow.',
        },
        {
          id: 'leaves.fall',
          section: 'leaves',
          cameraTarget: { preset: 'leafFall', transitionMs: 1400, endScale: 0.96, compose: 'right' },
          narration: 'Then the leaf drops off the plant.',
          caption: 'The leaf falls off.',
          heading: { eyebrow: LEAF_PATH, title: 'Lost from the plant', appearAtMs: 1200 },
          view: { stage: 'plant' },
          duration: { minMs: 6000 },
          a11y: 'The old leaf breaks away at the base of its stalk and flutters down onto the soil.',
        },
        {
          id: 'leaves.reason',
          section: 'leaves',
          cameraTarget: { preset: 'leafFallen', transitionMs: 2000, endScale: 0.94, compose: 'right' },
          narration: 'When the leaf falls, the wastes stored in it leave the plant too. Losing leaves is one way a plant can get rid of stored wastes.',
          caption: ['Stored wastes leave with the fallen leaf.', 'Losing leaves: one way to get rid of stored wastes.'],
          heading: { eyebrow: PLANT, title: 'Wastes leave with it', appearAtMs: 900 },
          view: { stage: 'plant', labels: [{ anchor: 'Leaf_Old', text: 'Stored wastes', dir: 'right' }] },
          a11y: 'The fallen leaf lies on the soil, still holding its wastes.',
        },

        // ---------------------------------------------------------- g. inside the stem (resins and gums)
        {
          id: 'resin.travel',
          section: 'resin',
          cameraTarget: { preset: 'stemCut', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'Next, the stem. It looks solid from the outside, so let’s look inside it.',
          caption: 'Next: inside the stem.',
          heading: { eyebrow: STEM_PATH, title: 'Into the stem', appearAtMs: 2200 },
          highlightObjects: ['Stem_Main'],
          view: { stage: 'plant', veil: 'in' },
          animation: [{ process: 'cutRing' }],
          a11y: 'A close view of the lower stem with a thin ring marking where it will be opened.',
        },
        {
          id: 'resin.cut',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', from: 'stemIntact', transitionMs: 0, endScale: 1, compose: 'right' },
          narration: 'Here is a magnified piece of the stem. As the top lifts away, we can see its layers.',
          caption: 'A magnified piece of stem, opened up.',
          heading: { eyebrow: SECTION_PATH, title: 'A slice of stem', appearAtMs: 1000 },
          view: { stage: 'stem', veil: 'out' },
          animation: [{ process: 'stemCover', through: 'END' }],
          duration: { minMs: 7500 },
          a11y: 'A piece of stem; its top lifts away to show the layers inside.',
        },
        {
          id: 'resin.layers',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', transitionMs: 800, endScale: 0.95, compose: 'right' },
          narration: 'Bark covers the outside. Inside are phloem, which carries food, and xylem, the same kind of tubes that carried water up the stem.',
          caption: ['Bark covers the outside.', 'Inside: phloem carries food, xylem carries water.'],
          heading: { eyebrow: SECTION_PATH, title: 'Layers inside', appearAtMs: 900 },
          view: {
            stage: 'stem',
            labels: [
              { anchor: 'ANCHOR_Bark', text: 'Bark', dir: 'left' },
              { anchor: 'ANCHOR_Phloem', text: 'Phloem', dir: 'left' },
              { anchor: 'ANCHOR_Xylem_New', text: 'Xylem', dir: 'left' },
            ],
          },
          a11y: 'Rings of tissue labelled bark, phloem and xylem, with fine growth rings in the wood.',
        },
        {
          id: 'resin.old',
          section: 'resin',
          cameraTarget: { preset: 'stemOldXylem', transitionMs: 2000, endScale: 0.95, compose: 'right' },
          narration: 'This darker part is old xylem. Many plant tissues are made mostly of dead cells, and xylem is one of them.',
          caption: ['This is old xylem.', 'Many plant tissues are mostly dead cells: xylem is one.'],
          heading: { eyebrow: OLDX_PATH, title: 'Mostly dead cells', appearAtMs: 900 },
          view: { stage: 'stem', dim: 0.35, veil: 'in', labels: [{ anchor: 'ANCHOR_Xylem_Old', text: 'Old xylem', dir: 'right' }] },
          a11y: 'The darker inner wood, the old xylem, is labelled; the paler layers around it are softened a little.',
        },
        {
          id: 'xylem.cells',
          section: 'resin',
          cameraTarget: { preset: 'xylem', from: 'xylemFar', transitionMs: 3000, endScale: 0.95, compose: 'right' },
          narration: 'Magnified further, xylem is made of tube-like cells with thick walls. Most of them are dead, and only a few are living. Plants use dead tissues like this as places to store some of their wastes.',
          caption: ['Xylem: tube-like cells with thick walls.', 'Most are dead; only a few are living.', 'Dead tissues: places to store wastes.'],
          heading: { eyebrow: XYLEM_PATH, title: 'Xylem, magnified', appearAtMs: 1600 },
          view: {
            stage: 'xylem',
            veil: 'out',
            labels: [
              { anchor: 'ANCHOR_XY_Young', text: 'Xylem tubes', dir: 'left', atMs: 2200 },
              { anchor: 'ANCHOR_XY_Parenchyma', text: 'Living cells', dir: 'right', atMs: 6800 },
            ],
          },
          animation: [{ process: 'xylemFlow', mode: 'water' }],
          duration: { minMs: 9000 },
          a11y: 'A block of xylem cut lengthwise: pale open tubes with spiral thickenings carrying water, narrow pointed cells, and a row of small green living cells.',
        },
        {
          id: 'resin.store',
          section: 'resin',
          cameraTarget: { preset: 'xylemOld', transitionMs: 2400, endScale: 0.9, compose: 'right' },
          narration: 'Watch. Some waste products are stored here, as resins and gums.',
          caption: 'Wastes are stored here as resins and gums.',
          heading: { eyebrow: OLDX_PATH, title: 'A store in the stem', appearAtMs: 1600 },
          view: { stage: 'xylem', veil: 'in', labels: [{ anchor: 'ANCHOR_XY_Old', text: 'Old xylem', dir: 'right', atMs: 1200 }] },
          animation: [{ process: 'xylemFlow', mode: 'resin' }],
          duration: { minMs: 9000 },
          a11y: 'Purple wastes move into the darker, older xylem tubes, which fill with amber resin and gum.',
        },
        {
          id: 'resin.reason',
          section: 'resin',
          cameraTarget: { preset: 'stemOrbit', from: 'stemOldXylem', transitionMs: 2600, endScale: 0.96, compose: 'right' },
          narration: 'So other waste products are stored as resins and gums, especially in old xylem. They are kept inside the stem, not removed.',
          caption: ['Resins and gums: stored, especially in old xylem.', 'Kept, not removed.'],
          heading: { eyebrow: OLDX_PATH, title: 'Especially old xylem', appearAtMs: 1400 },
          view: { stage: 'stem', veil: 'out', labels: [{ anchor: 'Resin_03', text: 'Resins and gums', dir: 'right' }, { anchor: 'ANCHOR_Xylem_Old_Face', text: 'Old xylem', dir: 'left' }] },
          animation: [{ process: 'resin', mode: 'stored', through: 'END' }],
          a11y: 'The stem slice with amber resin and gum inside the old xylem.',
        },
        {
          id: 'resin.try',
          section: 'resin',
          cameraTarget: { preset: 'stemTop', transitionMs: 1600, endScale: 0.98, compose: 'right' },
          narration: 'Your turn. Find the part of the stem where resins and gums are stored.',
          caption: 'Your turn: find where resins and gums are stored.',
          heading: { eyebrow: 'Your turn', title: 'Find the store', appearAtMs: 500 },
          view: { stage: 'stem' },
          interaction: {
            kind: 'findTissue',
            task: 'Tap the part of the stem where resins and gums are stored, or choose it below.',
            target: 'old_xylem',
            done: 'Yes. Resins and gums are stored especially in old xylem.',
            wrong: 'Not that part. Look for the amber drops.',
            choices: [
              { part: 'bark', label: 'Bark' },
              { part: 'phloem', label: 'Phloem' },
              { part: 'xylem', label: 'Xylem' },
              { part: 'old_xylem', label: 'Old xylem' },
            ],
          },
          a11y: 'The stem slice. Tap a layer, or choose one from the list, to answer.',
        },

        // ---------------------------------------------------------- h. around the roots (soil)
        {
          id: 'soil.travel',
          section: 'soil',
          cameraTarget: { preset: 'roots', from: 'stemMid', transitionMs: 3600, endScale: 0.95, compose: 'right' },
          narration: 'Our last stop is below the ground, around the roots.',
          caption: 'Last stop: around the roots.',
          heading: { eyebrow: ROOT_PATH, title: 'Under the soil', appearAtMs: 2600 },
          view: { stage: 'plant', soil: 'shell', veil: 'out' },
          a11y: 'The camera moves down the stem, below the soil, to the roots.',
        },
        {
          id: 'soil.look',
          section: 'soil',
          cameraTarget: { preset: 'roots', transitionMs: 600, endScale: 0.9, compose: 'right' },
          narration: 'The roots spread out through the soil, and the soil surrounds them on every side.',
          caption: 'Soil surrounds the roots.',
          heading: { eyebrow: ROOT_PATH, title: 'Roots in soil', appearAtMs: 900 },
          highlightObjects: ['Roots'],
          view: { stage: 'plant', soil: 'shell', veil: 'in', labels: [{ anchor: 'ANCHOR_Root_Zone', text: 'Roots', dir: 'right' }, { anchor: 'LABEL_Soil', text: 'Soil', dir: 'left' }] },
          a11y: 'The roots, lit up, spread through the soil.',
        },
        {
          id: 'soil.excrete',
          section: 'soil',
          cameraTarget: { preset: 'rootHairsMicro', from: 'rootHairsFar', transitionMs: 3000, endScale: 0.92, compose: 'right' },
          narration: 'Watch closely. Some waste substances pass out of the plant, into the soil around the roots.',
          caption: ['Watch closely.', 'Some wastes pass into the soil.'],
          heading: { eyebrow: SOIL_PATH, title: 'Out into the soil', appearAtMs: 1600 },
          view: { stage: 'rootHairs', veil: 'inout' },
          animation: [{ process: 'hairFlow', mode: 'waste' }],
          duration: { minMs: 8500 },
          a11y: 'At the root’s surface, among soil particles, a few purple particles pass out of a root cell into the soil.',
        },
        {
          id: 'soil.reason',
          section: 'soil',
          cameraTarget: { preset: 'roots', from: 'rootsClose', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'So plants also excrete some waste substances into the soil around them.',
          caption: 'Plants excrete some wastes into the soil.',
          heading: { eyebrow: ROOT_PATH, title: 'Excreted into the soil', appearAtMs: 1400 },
          view: { stage: 'plant', soil: 'shell', veil: 'out' },
          animation: [{ process: 'soil' }],
          a11y: 'The roots and the soil around them, with wastes drifting out into the soil.',
        },
      ],
    },

    // ================================================================== 04
    {
      id: 'whole',
      number: '04',
      title: 'The whole picture',
      shots: [
        {
          id: 'whole.return',
          cameraTarget: { preset: 'final', transitionMs: 3600, endScale: 0.96, compose: 'right' },
          narration: 'Now let’s put the whole journey together, on one plant.',
          caption: 'Putting it all together.',
          heading: { title: 'Back to the whole plant', appearAtMs: 2400 },
          view: { stage: 'plant', soil: 'shell' },
          a11y: 'The whole plant, with the roots visible.',
        },
        {
          id: 'whole.oxygen',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.95, compose: 'right' },
          narration: 'From the leaves, oxygen made in photosynthesis is released into the air through the stomata. At night, carbon dioxide from respiration is given out.',
          caption: ['Leaf → stomata → oxygen → air', 'Night: respiration’s carbon dioxide given out'],
          heading: { title: 'Released', text: 'Oxygen by day, carbon dioxide at night', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', labels: [MAP.oxygen] },
          animation: [{ process: 'oxygen', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Oxygen rises from the leaves.',
        },
        {
          id: 'whole.water',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.94, compose: 'right' },
          narration: 'Excess water is lost from the leaves as water vapour. That is transpiration.',
          caption: 'Leaf → excess water → air',
          heading: { title: 'Removed', text: 'Excess water, as vapour', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', labels: [MAP.oxygen, MAP.water] },
          animation: [{ process: 'water', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Water vapour drifts up from the leaves.',
        },
        {
          id: 'whole.vacuole',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.935, compose: 'right' },
          narration: 'Inside the cells, many wastes are stored in vacuoles.',
          caption: 'Cell → waste → vacuole',
          heading: { title: 'Stored in cells', text: 'In cellular vacuoles', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell'], labels: [MAP.oxygen, MAP.water, MAP.vacuole] },
          a11y: 'A small round window opens beside a leaf, showing the cell vacuole holding wastes.',
        },
        {
          id: 'whole.leaf',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.93, compose: 'right' },
          narration: 'Some wastes are stored in leaves, which later fall off and take the wastes with them.',
          caption: 'Leaf → stored waste → leaf fall',
          heading: { title: 'Lost with leaves', text: 'Stored, then shed', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell'], labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf] },
          a11y: 'The fallen leaf on the soil is picked out.',
        },
        {
          id: 'whole.xylem',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.925, compose: 'right' },
          narration: 'In the stem, old xylem holds resins and gums.',
          caption: 'Old xylem → resins and gums → stored',
          heading: { title: 'Stored in the stem', text: 'Resins and gums', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem] },
          a11y: 'A second window opens beside the stem, showing resin and gum in the old xylem.',
        },
        {
          id: 'whole.soil',
          cameraTarget: { preset: 'final', transitionMs: 0, endScale: 0.92, compose: 'right' },
          narration: 'Below ground, some wastes are excreted into the soil.',
          caption: 'Roots → waste substances → soil',
          heading: { title: 'Excreted', text: 'Into the soil around the roots', appearAtMs: 600 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labelsMax: 6, labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem, MAP.soil] },
          animation: [{ process: 'soil', mode: 'ambient', through: 'whole.answer' }],
          a11y: 'Wastes drift from the roots into the soil.',
        },
        {
          id: 'whole.answer',
          cameraTarget: { preset: 'finalWide', transitionMs: 2600, endScale: 0.95, compose: 'right' },
          narration: 'So a plant has no single excretory organ, yet it still deals with its wastes. Some leave as a gas or as vapour, many are stored, some fall away with leaves, and some go into the soil.',
          caption: ['No single excretory organ, but many ways.', 'Released · stored · shed with leaves · into the soil.'],
          heading: { title: 'No single organ. Many ways.', appearAtMs: 1200 },
          view: { stage: 'plant', soil: 'shell', insets: ['cell', 'stem'], labelsMax: 6, labels: [MAP.oxygen, MAP.water, MAP.vacuole, MAP.leaf, MAP.xylem, MAP.soil] },
          duration: { tailMs: 2000 },
          a11y: 'The whole plant with all six routes for its wastes labelled together.',
        },
      ],
    },

    // ================================================================== 05
    {
      id: 'recall',
      number: '05',
      title: 'Recall',
      shots: [
        {
          id: 'recall.open',
          cameraTarget: { preset: 'plantWide', transitionMs: 2000, endScale: 0.97, compose: 'right' },
          narration: 'Now it is your turn to remember. Answer from what you have seen, then explain it in your own words.',
          caption: ['Your turn to remember.', 'Then explain it in your own words.'],
          heading: { eyebrow: 'Your turn', title: 'What do you remember?', appearAtMs: 600 },
          view: { stage: 'plant' },
          interaction: { kind: 'recall' },
          a11y: 'The whole plant. The recall questions open.',
        },
      ],
    },
  ],
};

/** The synthesis map: one label per route, added one at a time in chapter 04. */
function MAP_LABELS() {
  return {
    oxygen: { anchor: 'ANCHOR_Leaf_Hero_Normal', text: 'Gases', sub: 'O₂ by day · CO₂ at night → air', dir: 'left' },
    water: { anchor: 'ANCHOR_Canopy_Top', text: 'Excess water', sub: 'leaf → air', dir: 'right' },
    vacuole: { anchor: 'Leaf_Hero', text: 'Vacuoles', sub: 'wastes stored in cells', dir: 'left', inset: 'cell' },
    leaf: { anchor: 'Leaf_Old', text: 'Falling leaves', sub: 'stored wastes lost', dir: 'right' },
    xylem: { anchor: 'ANCHOR_Stem_Cut', text: 'Resins and gums', sub: 'stored in old xylem', dir: 'left', inset: 'stem' },
    soil: { anchor: 'ANCHOR_Root_Zone', text: 'Into the soil', sub: 'roots → soil', dir: 'right' },
  };
}
