// Secrets check: no credential may appear in anything that ships or is shared.
// Scans source, lesson data, HTML, the production build, GLBs (metadata), narration
// manifest, docs, README and the pipeline for:
//   • Google API keys (AIza…), private keys, service-account JSON, bearer tokens
//   • the actual TTS key value, if one is present in this shell's environment
//     (compared in memory only; the value is never printed)
// Also checks that .env and credential files are git-ignored.
// Exits 1 on any finding. Writes ../docs/qa/secrets-qa.md.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..');
const SCAN = ['web/src', 'web/index.html', 'web/public', 'web/dist', 'web/scripts', 'pipeline', 'docs', 'README.md', 'blender/scripts', 'blender/mcp', 'tools'];
const SKIP = /node_modules|\.qa-audio|captures|\.blend\d?$|\.png$|\.jpg$|\.pdf$|\.mp3$|\.wav$/i;
const PATTERNS = [
  ['Google API key', /AIza[0-9A-Za-z_\-]{35}/],
  ['private key block', /-----BEGIN (RSA |EC )?PRIVATE KEY-----/],
  ['service-account JSON', /"type"\s*:\s*"service_account"/],
  ['OAuth client secret', /"client_secret"\s*:/],
  ['bearer token', /Bearer\s+[A-Za-z0-9._\-]{20,}/],
  ['key in a URL', /[?&]key=[A-Za-z0-9_\-]{20,}/],
];
const liveKey = (process.env.TTS_KEY || process.env.GOOGLE_TTS_API_KEY || '').trim();

const files = [];
const walk = (p) => {
  if (!existsSync(p) || SKIP.test(p)) return;
  const st = statSync(p);
  if (st.isDirectory()) readdirSync(p).forEach((f) => walk(join(p, f)));
  else files.push(p);
};
SCAN.forEach((p) => walk(join(ROOT, p)));

const findings = [];
for (const f of files) {
  const buf = readFileSync(f);
  const text = buf.toString('latin1');
  const rel = relative(ROOT, f).replace(/\\/g, '/');
  for (const [name, re] of PATTERNS) if (re.test(text)) findings.push(`${rel}: ${name}`);
  if (liveKey && liveKey.length > 10 && text.includes(liveKey)) findings.push(`${rel}: contains the TTS key value`);
}

// ignore rules
const gi = existsSync(join(ROOT, '.gitignore')) ? readFileSync(join(ROOT, '.gitignore'), 'utf8') : '';
const needIgnore = ['.env', '*credentials*.json', '*service-account*.json', 'web/.qa-audio/', 'docs/qa/captures/'];
const missingIgnore = needIgnore.filter((p) => !gi.split(/\r?\n/).includes(p));
missingIgnore.forEach((p) => findings.push(`.gitignore does not ignore ${p}`));
if (existsSync(join(ROOT, 'web', '.env')) || existsSync(join(ROOT, 'web', 'public', '.env'))) findings.push('an .env file sits inside the web app (Vite could read it)');

const ok = findings.length === 0;
const md = [
  '# Secrets QA',
  '',
  `Generated by \`npm run qa:secrets\` on ${new Date().toISOString()}.`,
  '',
  `**Result: ${ok ? 'PASS' : 'FAIL'}**. ${files.length} files scanned (source, lesson data, HTML, build, GLBs, narration manifest, docs, pipeline, Blender scripts).`,
  `Live key comparison: ${liveKey ? 'a key was present in the environment and compared in memory (never printed)' : 'no key in this environment; pattern checks only'}.`,
  '',
  '## Findings',
  '',
  ...(ok ? ['- none'] : findings.map((f) => `- ${f}`)),
  '',
  '## Rules',
  '',
  '- The Google TTS key is read only by `pipeline/narration/build-narration.mjs`, from the environment or the git-ignored project `.env`, and sent in a request header.',
  '- The browser loads only audio files and `narration.json` (no key, no API call).',
  '- `.env`, credential files, the QA audio fixture and QA captures are git-ignored.',
  '',
];
mkdirSync(join(ROOT, 'docs', 'qa'), { recursive: true });
writeFileSync(join(ROOT, 'docs', 'qa', 'secrets-qa.md'), md.join('\n'));
console.log(`secrets QA: ${ok ? 'PASS' : 'FAIL'} (${files.length} files${liveKey ? ', live key compared' : ''})`);
findings.forEach((f) => console.log('  FINDING', f));
if (!ok) process.exit(1);
