// Writes ./config.js with the narration API key so the page never contains it in source.
// Key source: the GOOGLE_TTS_API_KEY environment variable (GitHub Actions secret),
// otherwise the .env file in the project root.
//   node scripts/build-config.js
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

function readDotEnv(file) {
  const vars = {};
  if (!fs.existsSync(file)) return vars;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (m) vars[m[1]] = m[2].replace(/^(['"])(.*)\1$/, "$2");
  }
  return vars;
}

const apiKey = process.env.GOOGLE_TTS_API_KEY || readDotEnv(path.join(root, ".env")).GOOGLE_TTS_API_KEY || "";

fs.writeFileSync(
  path.join(root, "config.js"),
  `// Generated by scripts/build-config.js — do not commit.\nwindow.TTS_CONFIG = ${JSON.stringify({ apiKey })};\n`
);

console.log(apiKey
  ? "config.js written (Google TTS key found)."
  : "config.js written WITHOUT a key — narration will use the browser's built-in voice.");
