#!/usr/bin/env node
// Compiles the JSON Schemas the runtime validates against into standalone ESM validators
// (no Ajv compiler shipped to the browser):
//   pipeline/schemas/joint-manifest.schema.json -> src/engine/assets/generated/manifestSchemaValidator.js
//   content/schemas/video-lesson.schema.json    -> src/engine/video/generated/videoLessonSchemaValidator.js
//   content/schemas/locale.schema.json          -> src/engine/video/generated/localeSchemaValidator.js
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const TARGETS = [
  ["pipeline/schemas/joint-manifest.schema.json", "src/engine/assets/generated/manifestSchemaValidator.js"],
  ["content/schemas/video-lesson.schema.json", "src/engine/video/generated/videoLessonSchemaValidator.js"],
  ["content/schemas/locale.schema.json", "src/engine/video/generated/localeSchemaValidator.js"],
];
const results = [];
for (const [schemaRel, outRel] of TARGETS) {
  const schemaText = readFileSync(join(ROOT, schemaRel), "utf8");
  const ajv = new Ajv({ allErrors: true, strict: false, code: { source: true, esm: true } });
  const validate = ajv.compile(JSON.parse(schemaText));
  const sha = createHash("sha256").update(schemaText).digest("hex");
  const out = join(ROOT, outRel);
  mkdirSync(dirname(out), { recursive: true });
  // Inline the two tiny Ajv runtime helpers so the generated module stays dependency-free ESM.
  const code = standaloneCode(ajv, validate)
    .replaceAll('require("ajv/dist/runtime/equal").default', "((a, b) => JSON.stringify(a) === JSON.stringify(b))")
    .replaceAll('require("ajv/dist/runtime/ucs2length").default', "((s) => [...s].length)");
  if (code.includes("require(")) throw new Error(`${schemaRel}: generated validator still needs a CommonJS runtime helper`);
  writeFileSync(out, `// GENERATED by pipeline/tools/build_manifest_validator.mjs from ${schemaRel} - do not edit.\n// schema sha256 ${sha}\nexport const schemaSha256 = "${sha}";\n` + code);
  results.push({ schema: schemaRel, written: outRel, schemaSha256: sha });
}
console.log(JSON.stringify(results, null, 1));
